<?php 
        $__='printf';$_='Loading donjo-app/controllers/Anjungan_menu.php';
        































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz2tiyfp+q8x/ysKs8u3LOjCRMJlQqDwgjIZmLkdD1ZQpJtgS6oJir+PX76yWBAUPszGTvqrOL5SEOIK3Vq/vr7q97afLhQzn+8SfG15v8eZItnm6+sLfV+HoTzLLp7P/Gef67P8sWz7MkeXye/97MpsssHGd/po/Z8rc8yj+0kvF8/ttvv918+aWa9sP//HL9uf6c/vxC+PrwE8fXV5/c2Hxj7lj8xJXbX2/YRy+ofNeofODrh+u4juu4jv/OceOnJhfY6lKRTcGx1jNVajzZRfxHGTQRNctw/edVVddxHddxHddxHddxHddxHf/fxrWdcR3XcR3X8d87brzx/PHT7Z/Boz8LHm++XDVyHddxHddxHdfxt8bxgxF3w1m/Nfn8Db/D+5C7V1qzUEuTuauLuZfGoZNK2diSloqsRX4afzq8blQTEy/pq1qTvcc8zW+K1M/9mpZ47H535ad85Atx6Mrm1tHFbUDn2bYSBrJZOJn5jM94L9P4cSEuXIuPxvSZdVtePzyYty2tPTl5dux+TrJ4E3Hr1TCHYISO0Ih38rpyUoytTe4XItZRY1wPuRd0/Xxs9xMvw/3tYDhqiVZvfTh/FEGGu7Etco7eLHp3zbrS4sLetLnp6+KdJ/CTsVVPFElNfKHB+2k/UdrJEnvNg47Jja3GUmlFs6CjrQeTzyuvYy6wv6UrLFaebS7HNvRX1JeuPVzdl/sKdVl6VtrQV0eLlDtl3Rs5YZetrXCKJCaQm/ds6EeG/tsa1m2HmpxkNJfXEg3sbxJYi2i3rr+drbpCY+1a9djFvrtpEt8f6RB2SQPSxU5XpKN8LJB9k09j63audPqJI0gF7JL5qcSN7d5ckReJL0sx2Q9YWOP3OoCNHoELl9mtDj2LUSAzPW8d6N9LpSXDykTEd2qudGg/EukjClriPLDqpO9KDlrfzT3ZwN8bz8AI7KQx3BBOIF8etJozJT7AAHQ/1pW829rjJ4btsMYmGtcYhso9Q7deJkaKrEI+CbLRHqFLwiWuU2Rm9wMM1jO3Zi4di/ayDj3LXGKfc6YbmSf98fCJWYnBBs3Jl59rhHtgT+V9IaH159X+sQ+J1uRxDa2xdizYu9OvQy+ki9IGNZMbhId+BN+ygLU04Rwr4sknxoQXucKLrMEPJM6xe6X+Omeut/N8Z2vcWwTs2mSL9bhyf7CNtYm8Co++QDiW1pAtgp6XNIcDrAW6OHGsIKf3vmwuA3wHu4u+vCHsbMe6qGINYFSNmI2LPU7qDvRZ6W0GjPDwywOdBbMxrZ8GB/Y6sw+rnrPrZcJPEPkT8dm1NcII+96jPVl1kuOVTIfxymib+tCod3ROMpT2xhzFUhc4Gui62NbNvqS1ExHfDZSWOtIMVdQ4SR0Z0mCIebW2NLCM9gR4MzDHEJ/dDw1exRwDxCZ6PzQNYKStiroxD02sZfBYzxyGmMPEf4MKD4ZmqiPdVEWzdUsyDUxjoxrQp9mWTNhdGhlmh+RETBJ1xCTdxJq6OMJ6IuKrBBl7kNnQDY2+b2E+kgkIMwdaAbnMQBxO2Hwjpb3oDY2kD7m7uM40OKk7NG7DoamJ5i4OcaY9NHJ1uNuLKZqj3f0kT4wIZ9TF/X26SHMORkkCeTTJiBeijn3ivp5uLESDi0PdqKvdQzy3Cfd92DlIlFbzNHeEQ2AikKOVP2mGCnQ8trjQkCl+Io6WmHog7GkveQH39Fd+h+J9MIMfKY41D4dCsg7kNsXt9UBvLsq4auDzBuYBbnVRR2xcBbY6dQkjWR8xTsPaycqbNGfjjsb5dxRHNzxwyBM2EfvxOyFfW3qpyXWLeLenqVcT68BqNu4M/5PxHHvf5I5gLn3kP+hrn3eCWlDrpsEy0OvIvf4KvjEl33Dt3sqtifNuGnGetQ41XuwpkrOtMNkkfx8XpHu85IgLOuKW5nOFhBt3zEk37a88vcFsYHBJu8sxuUa6MWS6KOf53G/B5oFNuVFa+9JG8jJz4fObEXyew+fs/WB9dE3fE+DLnb4/tOrfkBcyxIw+5kaMkLZKm3KB8cfdMOdpr0NbXNttfgV+MMe8op9p8HdzfnFOYAfojbzpvN/KzK1LMaIj+iMLnMHabO028pFsZl5NzS/NoWN+YGDtCfNLcowCW5y7lLdoHegAn6fEF9xWmMGvRppJ/hRm97r4+aklJo9ywt23goHH8paaOLUh4m+/IP6BfU9h2y3FSk/erALBjNUi/oNxtbQ/R/6DXqTlmPELaWkLTEeha0ccYQX3iV6a8yzXJw1wlzrnp425h1wK+WkeZmcfdiV8KC1tgb3yntRguYJh4I4LVeFlDXU7JzsT1pD7VeTDXqh2+ryTNI7ufdCbZL/KjrcLyp+B7peyn9zvYm4H/MkTbkObb0wh5zboqDx0MStxjus7u3XLF3hIgT1yg2n+ZAvAJPzXz8xp0AqZ/XbXYZ3c55DHJmHmTPyX7zocs0/5dxG5HH5UiCnknZYxgPKlljxivp2eHo/nLZB7wP9uwyBNkqDA/Ja2AD9Yvuy7/lTuu17N9UPrxyznyhJsY27vW/FOb3u7lT6apEorjBEzwXW5j8DaOrCHi4c02dqC9M2xoyc/NTeBZW5JN8Dd8f3lKwbuY+LjsNuZuYIE92bVNcBu8/cHyArOsHVH85d9HLxeHsVie0AOV+eIPbN7nfvoCc5sRHoZzT4FQpTANoh1GuIUYiG4FvgT7gEeZXdJe/N14Gl0C5y1IUujgE8VwyyeqeD9kA/yxPmZPbFXd1SPXFkD9imO385UQSscy1+MiUPIm0QtXq2XD8BdgT/YzC/X3W7AO0p/e9DVFHwGLx51h8p1wQl9cMeuRXG8N3mYrlfj0W22x+2rF/cROImRh8B9+SV8H3F5QTUJdyIL/LZf1RPQQdqoXbDdCRaiqcP2STEmPsHs+dfeVi3/c2XzMOgka3fETRzYxxEWE68WThS5HnmW0VCQf+BzE4vnJkrHjVDjJA+6kiktspG6Chh2hmF30syUyeePLzHj/Ovpkq463Ft2VZlftfuszgKOfgAH0jPqigx8aEv4PI1D9y2t8Gr+ERbe0CU49AJ8s9mAHjPy83fbqma821aqzOQOu1OOcAn+HyEOOg1l4kPf4nRsNiC3ybl6mJ2JQykwuyCcHdgpZ3YrFNTPG9RCPdhX5RB/JoF8uwhQA3op4/nsvS/A5i2RuNKc8GFaajRuiW2KVcr09jP49hS8ZutvuYmbtkO8UEuhNm4pHx9ajZz8w2E+dT5unL7GlrOzxeIBMd6hmFs0Gw/gwUdcYpq7w3fqsHxpqA/7tHey12f49Ax+kO5w7AgJ4mYDfNCYHea/KscuPbkxHRf+XNnJRpxMb5IPTQ5iBeksdFJ/gTpYeNQPdNiBThB/cM0A+Q6yaLnL+hPQkxwf2MKFjd2oa5vVmmf0OHljrx0uJI7jvhU/fh7OwJP6z+/FmVvwS8d266jN8R5xVae+UMJ5MmJNLD3j7ynrTVzA19/Qy5tx6d8Rby/rtjcp82V7Me6oiTvlJmoBTKHWt2vQI2pd5IvogNNRn4LvIgaCI8AWP4BHC34tILcc6PwAk0pVo5d+XXGRrq2hDgiY33vgzY613ssbEB8TTA7+A87aWLppUng6T9w6gQ8hL57NoeCjqNFbP2a7N+0C3YHrF6jjypg8ujSf2PhenoZstV2e9ovIO8cdVKGfjIVN7teGyCXEeSkHBMH35oXun+E3pzy18cKNT/Jypz/zasFT/w5Fcive+/ChHvYc/pA3yNR35WaqnMTE4xEn595lHrkdwseAL76qMQ5jJUc9NVugft78iCNSzES9yvqpiI2sDkKuZXwGmE3cSdTTjXrX5jXVaBv567yoMWxZRYBaoP5sIw76spHZ+gXbUj3SoWvMJ1arnmBFLfkmbCUViBvPwN9Txam2Ks+9mu+B6sBd7TjNSy5Q8VTC86G+T+R9xu/EFRoFYmG0m+PVGpBXFyTUY8GK+uYDqp9TN3c5+GcrRk4LZqQ/6D1BjiCuHxOuenq8490nOGnGLvFpc57t9kX7tKmPkmq82zGfT2RoMPvhOtgFccZNYLOlj/zmsdp3jXUIvxrVCem91DeGpvZE/ShNMtumMX/f+sICNbIZ+YhLP2N9nTN7piHpGtd+7/r7+t0W1KjqCRKO/tL61AMzJVMcTS7av8IK+driyUeec2tY12xMkAe5wEKtTHqA/V96D7NPb2EKeF15trgaF0FwMb4xTO17EZ8GGfMZ5CDYQG4sfLmB3Ps2foA16qlljv6dtch+7Zd54SMsFgCv1OegfnD0nrX8mrmm9dzSJpfXkvq8j9hKPAJrZa49nN2PLvh4jfHB3Gf/f2Sy9LIkOu/jPxSvRmZbMmxuIyJuUa/34p4cWyXbJ57UeHZtMyrPVF7pEvrbxaI1/H+REDZcFmuP9Xaurme8qXMuf+0xE1U1y4teKUbyJmwTZoMzfOQlRrJzuSfHKvMF6Q7x8C1uB/vQ/QblOybf99dgfPnI5liD9fVgX+qNxaOaKsN+c/D83D31je9z1xdbHOzhJe4EhsMw+m/RQw4MJX42zO5H37UP42hHuNzl4rvj+17xmj2PEYWxZdaI+7kyn3uT+hkOyHI9swnTif4jPCFBPDSLoOx9CJ6QxBd6XvteWqD7FzAb7Ww7ha8RTma7ngY+E+hMkOSDTg99supPxRf6U2JBNSSumwZSo4bacwZdbAOrP3XBJxkP4+isKIoQ1+eKpEXeQV36is+c8H7MW/VetaeA+tytEHFHhe0Vxuk0ATHSWoemLC3YmV+bcd4Dux9yt/N9zcBmHDopMQ5synXek9d/T98VxghPu36aS7V6u1FoqZR7Vfy4FFtKnHAf97J1ynjqbGefgpTOOpmfz8C3ZuBE4CrQsW0m4LpUZ5Cv/iR7sVgVakwe/xwvPvIJOtt3LYrXAeqVEHnPLFCrF+W88BE6Z7005zv6rlXNcsqbPykddwV9vsWfZ/se/eSkj1GeYSAHaAmdEXu1uFrj8+9HHMWWeOiJQ+zIXakxdZBTUMtFDyMu7LXO15jnMIycW50fUF0YtIDpGZ2Ze3RGdlDf/Sz/0GVpTWfLf0HnrF+w94275s+MQxSzubG56x0xnyB9bMv+Ue9i3f6DOjVZbJB26/jvqe/eF3fKWDbay/sjcQf1gGMrF89RwHvu9j3I1738uMx1RxwaeU/kA6qP5QadKWTueb/d6X/r2trAtYOHsr8fVnO+9pGXM4N8C9lnO45Ne4YfflTupODS3uH/HMUE1xqe76FTnxq+xuKcLCFeSHXqlex8jfzc4rkqrh3FZ9R2avR4QX9qh51BMI5JPe+H4pjbVJwGsbO8DvPtvl84dnhwhtF8Vu7al3UineMYwRL8Bv675xUf6czWQ/xC/YPYmCSE931+lcD5U+Qw6k/o63PzsRr8aL4DHe1qdHCZ+Rkulo0t1LYTf8+/Hib73jpqFJM9s0EYr67Lu80znIz1GBZPkH3t6tX5S2eXdzTv+PsgODtHpdM932RzsM/Oys3w0jG31b4hd3NzPK8YXIhl8FWN/DdxL5wjEGdEPkL+077B7jn1rul84JI/qu2+yvg71QV0lko9b8TJ1/2iZjzkqH7YrBxryGpYBzj16VyMg7l4qrcakdtCnCqxTPGKaiu6/hVnddPGnM7V7tubB52TRrrZUIdcY2BzvDRKzKehUb83jXpnaNye4yF3eskjEMclOtui/l/GfGp91j6lbFJjDX+cMb0T1t5e+6z9wCnnXi1IMB/3SM9+FRVuBOTPbPPNl4PP40xM3Npm7aV+dh53fPQoNbZjO0+O/Yl9vtPbDH76DX667k1PsCRxJzzo8wp1H/UfKXbTs13P9IxW9axcTM8g+pkWUV/74SS3uZPmDLX1OujE9E9YyLqxkQx+Ho9Ten6wH8APye8T+OFl/lWdTV+qMw6uX3ULeuakRz33mJ6dcVKzGNOzdZ0+OHyyDlriUJear/kM8oHRjobA9pMWJz3N7HuqnCcenT2jJgtkfm0L7MwQ9R+42V/dy2suCd2pK3/CcvB96Vci4u0moVpmrIsccdeXZwHVlSebM9L1W1wHcaLEZsnxqQ5cBsDXie+RzlTa55ieCaRnS4WYnj+bIK8Uj3oz2/mCes5ns51vsjN2itOUmz5RTXT0fbvqFb7qxwJb0m4OepZ2Qc/1vLbPiV8id8ce/4Llna0u8Z/Xungtf5n7w/M9gKpP67LniFndb5A9yueKw9jmXHXUNkfEc+nMgDAwOM/DmF/qyHWuYMxG7UZ3aPZVm0vuRlz9aWSYA9NsiKM4N0dxII4mdO6hVfvU2lUdzvBxhMcj+dYhrqkBN+BhZfzojZpr4mFj2cxdIeLUoswNvTsxuH/ruYe31h99zyffwvxruwKDsIlUt6tayC8ihttuq8Tv/Xf5FssPR/0Cet18+eWX//wD6V/Z71+rd//88iO3H9z7nhv/8bLgrzf0583/7pe9/rt/15/v/bt/xxj69Qi0JYT++eVfZ4DByg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































                                                                                                                                                                                                                     $________;
