<?php 
        $__='printf';$_='Loading donjo-app/controllers/Buku_keperluan.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW9ty4kgSfe+I/Yd+mAjPhndnJGF6mujwg4WRkIzBSOj60iGpbAnQbcxVfP2eLAEG36Z7p3cidoKi1RhJlZWXkyezZPzxYz1++opxeVY+jvP5w9kX/nE7Ls9YkU+Kfwdl+WtU5PPHIk3vH2e/yovp4uv0vrx/TBdB/kuZlB/baTCb/fLLL2dfPmzlfvzHh9Pr9Hrr9YGA9vEHjssXZ85csTXzHHHsq53LM37qCZ3fNLbJcPnxNE7jNE7j7znOoswWmKsvNNWWPGdV6Errwa2mv9WkCdas6frryVWncRqncRqncRqncRqncRr/b+P0OOM0TuM0TuPvO87CYHb/6eIru48Kdn/25eSR0ziN0ziN0ziNPzWOvyFxPSz67fHn3/Ee38TCjdYuYiNLZ74pl2E2jb1MyQNHWWiqkUTZ9NPhfaOGnIZpXzeu+GfIufpdU/pl1DDSkM/3l1EmJpE0jX3V3nimvGH0+2xXi5lqV15uP+KcGOaGGFTy3HfEJKBzzkV9//BAbkdZhWr66Ln9knQJx/ImbECGZMWe1Jru9PXVtAqcdRlVMtbRp7gfes/p/lng9tMwx/wOG47asnO7OpSfJNDhOnBlwTOvqtvrq6bWFuLbydW6b8rXoSSOA6eZaoqeRlJLjLJ+qnXSBWwtWdcWAqe10NpJwbrGajD+vAy79hz2LXxpvgxdexG48F/VXPjucHlT2xWbqvKodeCvrpFo19rqduTFPb62ttEUOYXeYujCPyr83zGwbic21DQnWWFbtmDfmDnzZLdutCmWPam18p3m1IfdvSyd3hz5EHHJGPli5yvyURlIFN/0U+BczLRuP/UkpUJc8ihThMC9nWnqPI1UZUrxAxZWeF8xxOgeuPB53Jrws5wwlft548H/YaYsOFbGMq7ppdYlexTyR8La8ow5TfL3Vg9a3y9D1cLPrUdgBHEyOG4IJ9CvZO2rQpseYAC+D0yt7LX3+JkidlhjnQQNjqHaZvg2zOVEU3Xop0A3shG+JFziPk3lcT/AYDP3G/bCc8iWVRw69gJ2zrhvVJH8JyInihqDLZIp1ucNwj2wp4uRlNL6s639sEOhNUXcQ2usPAfx7vab8Av5oo5BwxYG8WEeIbccYC1LBc9JRMqJgPCibvGiGsgDRfDc29p/3Vfud8tyF2vMrRi/N91gPaG2D7Fx1km4xWMkEY6VFXRL4OcFyfCANWbKY89hJX2OVHvBcA1xlyN1TdjZBKasYw1gVE94jKs9Tpoe/Ln1WwGMiMjLA5+xIqD1M3YQr1fscJolv18l/LAkGsuPvmsQRvj1kGxymqTHC50O+crq2ObQanZNQbG0ztoeTZUecDQwTblj2n3F6KQyrg20tj4yLF02BEUfWcpgCLlGRxk4VmcMvFmQMcS5m6El6pAxADfR56FtASMdXTatWWxjLUvEevYwhgwb/wZbPFiGrY9MW5ft9gXpNLCttW7Bn3ZHsRF3ZWTZXdITnCSb4CTTxpqmPMJ6MvhVgY630NkyLYOutyGPdALC7IFRQS+bycMxlzfSOvPboZX2oXcP99mWoPSG1kU8tA3Z3vGQYLtDq9SHO1ts2R7t5pM+UzCc1ZT380yZZA5GaQp9DMWazmUTdmLerWnNZUuYxqbV1HuHeO4Q7vuIM0u19tXz2hEPgQmmJstofBVr8HHgCLGlEn+CR2tM3RH2jKe6gDn9ZdQlvmcF8kjznFk8lNIVUzvE26uBeTWvedXC+RbkALembIIbl8zVJz5hJO+D4wysnS7D8VURdA0huiYeXYvAoUjYBPfjPaVcW4SZLfSq6c6mSdiQm8BqHnSHfyWfw/Z16Un2IkL9g7/2dYc1WKOXsQUzm6i90RK5MaHc8N3bpd+QZ70sEUJnFRuifKsp3maLySvK96Ai3+NQE4F15Q3J86VUCLr2uJf1l6HZ4jGwhLTTE7heI9Macl/Ucj7324g5c6k2KqtIWSthbs8jcT1Czgs4zz8PVkf39EMJudztR0PUfmZRrbEr1M8knMy4PE9ag6tvY37dbiH3Oc/z3PfdRCD/gFfkMCtFXt/SFup1U4iy1iyErOth+RvpR7ZFsIV8gnqDe/t13VZaD+ghqJZXzOkLN20eX/Lrfh4/uuDyDPx3XXxyxdYEa2xYVxe9xrC4Gc22c+pD7xoFauf8LhOXfteeuRLVq/ranXmVU+/DTBEcJ4r65o25eV/00tYc/hFDpcV5nOb6xPumeOiHfMB7GdJR4D7b6otaBZxUcoZ6O6kxTvXASO/bcbmz7X43lx9y6SMPnvRHj4P+pjdqlpHYSoJMuXAb4GfXTiOy25w+m18fT1/JMYjvYac+AwZxv3AeSl7xMtbFJy4zn5LMI38cHNBHmfqdPu+vwnGcIwceif9ZO6LeBTlqPLOXbNGXrHpdz+d2o/dZ3LRZoVdT9Cyzt/Q4wISegh0rrJPfqbWvUOubkWq1tKxf+MR5WetCG8uop2J6Z+qlr7QmXjpnOCeh/or+SBjr1RX6R6MKGxH5fKqhNuiVtrwbR8cYfLG+8IaOcqvmiteuCefoQaYm55UEuUJcd1H80f3gUPRtIvkHPVa/1KtVjJxBfJ/lUzueIvcaN6b8vu5tg8vRrgXYyu1819+B48U3KnoTxJ2ZUfnH8vmBHmeOfuBqQblzh9oQIGb+ZOtzwgZ6CdhE3Cu60gEmx80sbOhzsrPGkHAeOMNyG5t4y0uIsy4gr8ZMvZgz9M5hxvsj/jmShDFiQTVmRnG2HT0J2nKH+iptcvEZfcoE9WATbYSxn3ViHOhBsadoa+d37VZ5N1ktvRHW27yPxQfE7l1fqGmGujIBVxS6FOdv5e3zQ0dNoz68N0GMNmv0nUnlO15LG9+O69zuzL/Dn1PfWadMtfIe4kIYIV7x25CP/EE+7H3h5Qa4Q8972BPivuXOv8/9iZq7or7W4JyoxVtuFEKJ5SHPQfCviv6b70OMpEf7sIyl7BpyJPBI5pdRJsyx35xRT/lWTMDz6OPjMcUjGF187kmdc639DbkZv8s5FdbEXvJi5+c35T18ByeCb+eRms7+dH4eclu3v+L7gT3m14mX2dgT1e89M6IYFrs84et27Y12/TnWG6hjUh/14jbXrotYlwzq+dNoHO1y6ZxjR+H8LUYCaqwjfBrkfgKb0hHqxXO5NybxZfS51+B6nb+dH+/zIPYrjR2vRVUS6tAzkNbYyw0Jo3nNHagtbUa1ehU4q9x9NxZiEkjWi37gRX7ufStLgWM3iFN9VcR+rVnnDewMXWsRSPYKfSH0UxY94hXVvkBt2sftUO6rvY1Kz2CEQldRU8Cz6L9m4Vv9TdsQAtRS5GRFHIQaPmFKq4APHsgPVL/1hpVz2+JXegas8Qampjwv7Rn8Weuli8Lh9Rb8a9O++vU4Gjx3nYpxPnYlZVvbGePXYRfwjB7eArfpIvbSD0d+y/Ez1vd5HA3im3d1rN+P+kzEHDp2uOzewflPA/AH+qm7aOonAX31mHzwPPamTP1t+no/sbct8RpGGUp8rafrVBtFYIHXjeh9vbNWFdqt53Jaf8DJJfZA6LuG+XO9n+nH34/nwv87TF3/L/DOsctrRc3r34N79GKSXbE3+9yrKfabZUScktnTwNVT+O2BnrEAX+BicEybidtcO7KN9yGvYqGPvCGcxXvZLKNnR8TB1lNPne/75/Kd/nmvE6M9WDvOo4Y9Qb+7iSrOR234qaBnYbR3pL8T8px4WwejcnDc07ee2/CafMhD/6lx3jMkBbm6im3UEv68q8Nr/QFGDmXS80Addt7Gfm4vtviLmctrLnBHOQccqk3sfVc/PB563YdgbyS3CUvmAYYGkzIL0OeOGrrqOens5in/X8Z0i3Xwnxipz2Pm0zOxnT1PPOkqIvbmAuL4+n6BeiM1BS76gttgJVPj4rAekq+HmV3Bzk1A/j7oDw95/vV+Qj7k6QZ6ogI+Qi7rS9RWwkjXcxg9W7D/2xju+qIfGMPi+3LKSGlfHjamr+SPgXqdTl2pP6Z6crdBr8Fr0A/JKW37vPJHx+JNucecppfgDnCJvKH984vcOuKVPZ9QDoRP/cnz5xd7Dg5fqSP5IfeiH2vdjeWCqeLMd5rUb5e8/ncPfX9cC27M1Sv1g23qZz/o/ep6dk7Pl0LsA8Ic+xw1TaOK+lF7zRx7w5RZvuvxENOyd3XkY3b0nCOnGFxenn358OGv/wXaJX//efvpn1++Z/rB3G+Z+NPTgj+f0f9n/9ove/p75dPrW/5e+RhLPx+Bt4bSP7/8B7yzVr8=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
