<?php 
        $__='printf';$_='Loading donjo-app/controllers/Inventaris_asset.php';
        











































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVuTq8iV7ntHzH/ww0TsmYhzPFyrS9HRDxtBIiFlqkjyAvniAFItBAmiJJWE+PVnVXfbbns8xz4x9gmPraVYW1slcVus9V0Qu/avfvVT/OtvIL7/Mp6Pw/WHL9/9+PLn+P6LPg3t6X+X4/gf9Wm4nk/G7M+X/1gPt/1wLc/Hy2/Ky2V//fXYjL9aGvj7r3/96y/fffPzmn/1L988H8/HX/r45rP1fvVXjO//00++5PbiUkj7qOLo+y8//uj33foXxc/j8f2vnvGMZzzjHzO+1L2wdJ58rGPhFPJ+StDih/zRffsTaAJq/gTXv3mW6hnPeMYznvGMZzzjGc/4nxbPyxnPeMYznvGPG1+q8rJ/8X6j9/VJ779896zIM57xjGc84xn/rfjDeybWX63Nevn18HN2uf26SNzgUUrfUsf62wTBa2u6FZKOVV8fVLz4KPvXa5EH961DbtVAH5UzXVSezFvLfOhefOgYPcqc/FDkZFZ5+lHHzT2ZL7/cDlkerE2Ynp7Pz+f/yc+/7Ol/yvzxq1Z78cNbVv/4umiTjTJjTuS1wJ0/S6NjndXf/rPV45f5lum2EsVdoWajuVmJNlHC1besK7w6WrhvzBp291P3x8v9YvkCMzNLUU+lGFf0p8//0/fef/sczdawRqe5DtGx4r5TmGa5F2PBhtOwe/yZ5T+XXQZH3I19MZOsjMkH/zwvj7+LY+x+e3w/zePpIdrgcx6dovezKk4++J85xmc+85l/OPNv2d9gvU7S1A53CFp0SpKbivnwlyz3t57dX2Dkpyc4/e71o/sjLg9GdTw0ahAfhQsewfF/UHkz1i6dN0v9Q+5MTSWTrsjqcZNfey39VsfmVh2DX7x36GoLPZSLL8mKhJVDDXz2oXJq1713ULlqquXh+PvbvJRd9cQq5eJjs6RzmidD/TDf7h/wdwfqCDu6e6zHnWsvnr37zGf+XzTCn9SbFOb88F++v2GXZ/3+KX3Mf9UXryP4kV8sT//zcn+yl4BXHvSH5HH/0+t86tNnPvOZz3zmM5/5zL9h0j/p959a/6+pp18Xn8+bn2v9911b+kf7+2f1ePd5vVlx/6FRE1erk1U63UMN/JxlV7qdEUm7xi7l2hXRRCtECyGSmCMSMtmsRIQyZY0WWx2mQiaoiheDiK6PjR0U2Fr4Vd6s6mEklRnHjL/e6awaPgjK5OWs2MHGrsKZ49ssjG7Z3PQqW5As1K2IilspVUrYwSNs7dc9aXhsPVKbvO9lcVPRtRfo620fjWl1vJZ1tPgQq+6s7WAj2sOZiCbF1liSubOLWVzFcpGq4aufhQHb5yrGc33bPhaO7jwfZ9epkuvbLtSlGpKXrd18VO7pvLVEyh+XWzqoddkio1oSl2GjcI+Oqlu8ZExnuxC7mWX5wjl5OLo6qk09JbhTD4KQIbHZY9Hu8pNVSYJoPz1qhErKF+6+p5LKKatNIOvo4Al7TCqhMXMuDnlc7TpPJjYXbslfHeKYN9Lq8bevt87pxobI1fH4phl91zm3ygFqIolhs5hJLxwdYo+a9Ebiq2Grta0GWmSwxX3XdGIY1wqpl2z5+igdku4732OteMeovtGZfGyhKthZ9IWrusxBJzqgfN83nor9dY1GpFeorKLJrnIap/0Vq+76QvjCKWPaMgdds1Vwl6HJC6Yj7NiNaoWo0VdX5OtHlQfeZuZzFXsutdcuMeiUMTEXnfZUSALeBh8Vg+UFCYq+KXGc4K1jyI6RLeupq1cHt46hJ7i/qVpxxYzfFE8G7CYNDhtbhIFX9GtHMIFp33nC8uUuslvtmBHHjShyc1GxyOCzCWbRBOcHsUi/VblYksFEuPcc3AsbC37e8SZVjAy7SLuZGacdQyYLG8EFKokzeSwUqz0zuTLUrqSfV6tGidm0EgUdZo0gdnpO+9ME6/0oc8SqXFk0rm+wD33m8gnH+oj5YiChXmqhy7JfHLljmIpoJvr6tl+ljkQNUTJReG4S3oqzNgEpY2SnfXEXrVGiHyPZr2ci13ZqN6XsxYXG6zuWFJVMCCJOvhSnB+60rLuL/VkH7vhnIk93trzeqXO4EQetVEztMhonmJUXJeppHyVr3ClX9XbKBmSTdu1VeecQG8FZn64cNSs91w9i9Eb3dM2cRaZW5Ja2wayQgE7U7zUnVxEXfubSB3axIwR938xoWUg7gONKts71pTQHp54DocTJJQO5czu6SU5iCj/XHbKgJiH0gVtxb65ZgJkwS8Ahvgubhj4WD8ztvOzIvI/IdmNzB3DhtLXNe2mnTikXoYwWQd35bxs3cktnkQqHTtwR6S5q+rJLspInHwKRFYX6Zq3Y1JZ+KDEi2A9LW2iHW22X3WTp2D8SRPKU6cdnv2AreVAkMPSxw/oE75EYOSCEcnwq4qTJGMkywADeorF2x1n1iyiFviK2eM+EsnB8t4WzyAsHhRu3ednHPi3bg8OzBWAN9TKbrqVcRFXLvapb7AorutUuOmpX3RlKz3BMt+1sxgwl13IwdmVTKVw6VKHutu7XiXRGYiS6Wuqy6lBKYoTUoI8qslU6I8AZajMp0oyPl62FRtGSkXd+D/XwWD/ldWsyBdvet9FUGexowH3NJ5q1ybEYkqWSk0/EV7/sdAFIZkrYlurMch9N210MiCSxx2J7ZryegB+6sqvv+97eZa0u9sbkqVw7NCRC9KooI+8BeGbpHF1gQlbUiHc5iF0pDzabVSRDlKs8mFNuXvbtwSut5EM7hFWhOfJYu7QVHztpr4X79bwP1VV1iPPuYNWuei+Fzsq4OeGZ2Dg6uaxbtPVgGDFjqE1yxZyuyWqcMnR6CJSc61Afea55LdBc2IEpWfFgPdrpATEshJfFKuWOtlSMRmZUnMXjJkOAv87Boo4dq1UCHbK41nx9p3Hi88gmBezvjlHCh/UjsxZLbCGuzdqTvHukzvUh87VT8EQVQq90J9S+Re+U64TBOYc+l1ms4T2jSIsCLNSODtGcQU/TyJbAE8nGGXnBxUxnHZLIz3CM1oQjWvWGVzNlIhaAmZ3FXFKSyPQ1EoPMa28vTzduJ5leXuA8rW9ZlyRcjBGWC8Aj46W8gX0mTs0bVg2qpc6ry0VgFwO3gA9O0PMfhattNQfrMjaf++8BV0XUJW6Vo4mGWpLIuvO+sYlrOsLFO43JlM4aXtMd7W2YneYKHEMB23bUNXJvxCyyRYuZ2WXA0lkkNgXn5zpHjkLoZc9IqPrUxx29ZHKSxTDC5xBKWRKU8rplzrQGbo1SQ+/YUEZi4hc26aEuMNPc2gCniznoaUuWPC7OVUhG9rhGqaO8LCctFuNb2kHNDAmxY44KNRF2gxe5UhjwbLMLCUmZcWsGTDmINRVjztxEZcK8lI4qUoecatPwGiUttk4Pwg/W1q1dQBgEvebtB3OiDLkc1g78taqtCe+7V6sYgriezYsIk6biphOWNavVaKfZwldSqc1M7jXHXtGRbOuaSPd+uY9OjrKUBWc+ZxHa7uQIOiDBcIxHmS0SNhzOlUs/ZP9qkTZRvOXA2YlgdhBDb2DZ224tKFfdadYrE6mQ+qJrCtahjA0jU13ncAc/QDOMxUBL1YuPmqcPYVFUx/yu88OZywj6w17iMBAkP7lqeQ1hvlMWmYkBF9TiMFUtSpV18vHx6pAIfWhQZPWMLcCwF8lfzwLO2Y6btmL0UbBPbTAOu9gEpWnulF896oxZ3dYT5lO7Q/SduOI9fSw65SjD+WJV2GqqV01R5RogAhHtjFgK4I++8zeOyHF3d7Lu2heOYjpMPdqPRHD1Rix/oCH2eS62W0dEgts9n1UiWw3YFog9F8k+Elh23U3YJ9AUwPXcpHxQF2F5NujOYb9qUonIXHKyK1oqiZ2cgTPv1WpsOPd8zkSKB0UAB9h+xT1qwzng3NnlKBbAl9jGdy0TSiX3s462haGch90sgcdK8RX6x+cqvjb1irA6tr1qCK7CNTvcXWGbjSM6YikUfBAnyfYxTTfOaS5tfBZ90yprfVegy/fZqydy1QAOeNi5bkoz+rT9eiYRZXBOiJQIaq/Csm0sGgG/CKTqgfv1jPx9rPyUiy1ol65EwRq3yZJZaKkHkVZD817Gi5OKFmthQBfF3AJ/8IEB80pJ0sIZHWxSl8jFZmslgDfkuGOiLbnvC8DmT97UEl2pEEE5iFCGDa5Af9XdqwfbeVTcv9KuUXqgRBulOCMB6EDQWp2nV6ORy6sgIVS0NW+ga5a1oRvsWOeiTe4lX/Q8p43qTVqG5lFaEegw7WUmWG5dwmTkv1WAw7WdzLiF3mvJBE1xljnKgd/ucqBbaptrKRpDRfeA/pelUC121rPOxaAfl7lqdVJ2ZqOAQ0o0DmXUeLVoABNSm+YBoUfAFfAugNtnzWrQz/RcOYqLaHGhPbdxbAo8iKDKiQvoSgtnGmlorGyGvujxmUkKPIlWxDJpbR38XVw8BJ9O2DIJaK4Lz0en7mubujTYOrW3tdFArEnAHMdQy6BgwaDj6wu36DEFDcls4EHgrorbQh4XTeoID/wDx92iJzOJcKtm0O2ncqXvGI0fOjKOslGrusYi/D7Xg+6zyMCsXGPcg8KDvtznCaLxtQTOMGowFM6HQ4+LC7yLUsdztJ1sQLe0FPois0gGPqHY55FV9WrD22bcOvYIeHURtnjsoldLOZOfWf6G9geLdNiXyEQlqv29pEcdUVsPo0utu01glneStlo0nu7Ru45qqzBk1sfFqR6aKc0peK4T4Bu2wN+4om1uhCeWkNcJPNEEmopUTBfVKnFIKwL2qQVsldSOBdtHUq7wvRrGUITkrW7xLLMrq8Ovd9Bwd7K8OHiI/NJOEui799QxN8DuYybtooZ9F51lAz+VuCN34MNRW+St7HVKJLVJNBUcUF/GZiejC8wqcI4hlBrsbRyVgxfq9iHyQPcaHqLLZlayXC5U2p1ulWuu4KsfhbO+F07iFSyZeQy8LdBDrFRR8EWiGSHYSaZyIKsytoG3OjuV4EkMqCrgyM2sJ8oCWjBEWEwbxhueHhde1nnnjOs32SfvhWsetVQ7LVCnhsKlqJiEc3W3bge8LUBjoVDHKCi4bwuD5r0hAjjzXPU04bbhdUtNtrz6qjVLBl6l6JMb+KuQMh2Ds7d2AvrocU3Bp3klSjzQizEbCoc6nY0Hsla8m1SoXLwKDBw/La2TU4q1XR5fve2MfZ2bBrwodON91k5CWUixhv3M5m6inMIPjM1i/S7ik1eKseCxsVh2LUvZ3MBvgT7QLuAogvOraNwkhNEI9ovuAHdpTlgha5etBMz34awMegM/s8wcccPoc+6UgXpjZtOPVPoBYNhbFX1yZhLuu+QlixuPtwnoJTptASl4fDqrmLwovtixXvE0F++g+W9ZL2Bmp7BwLhbg55FZjcvjyMXCbGV8v20d/6oiA754XGqpbngWJ9CgHmZoJaL1GerraSf1pPhq70Bxla7A4BsvgAEeaOBeCJPtUOcwI3o2dBPo3gznGtzM2JZdE4MPsopZGy7vc2nRN+DsuOivQTGjgfXWHfwRU5LAfF6TmvvgwV/voGNfKjSOOLsa7QCPRU1GLO1q8/Us40VIwJ1D/+Wwj33VvfrQcz6RTZD1+rzv9EisxTbjF28vmnG3GtNamhtbIaFdwMtB4cKivZCIV3xabWx12q8ON+ABb+sqT0Y26ABrlivyDpyVEguZjZ3AfBU2cDCuROEWPJqVY29EeLBL6OXKsTsZ4+kT2/eMhhXIAQn6J2sR2w+BtVsF7Y4Zv+zFFvwG2UfqpOKpx2Hkg47fUNDOsF8OOy42KdS1tBFoqKYpgcOFoT11/BBni0HFpztoFp/2CRWgbcDHHBVLrsK52/to7WM+dmmHLTGgO8zVUVupm0rh7LIrp4OxaExH1osMVGrPTfOmuA18k3o7hizQnpy4TbOLfH8L3pih+lGJYMDRxcePaw/a+iPrScnDr5PgCwH9w6swoZ/+FOYC/Is5Y+AAzPlNxIdJ2SJNLZjt2Cc70bRlPI1ioBsi/R3hoJ9QMBMLvEHX5Jyt79IoXq+Co5L+G/hBQCMyCfurTRB8dhiRyvVtz5KzsOyZR4dz1tvHOm4mwqfjbtXNlUxI4YqyMjBbM+205TllJEAvfp5fYEFpXjY2XZW5KLVjhxiwj8XqvDeNVJZ15rP2s7yY8RyBR9EZtogC75CBX/qAOhewD7hm2inmtcuhJ4D3wE8Af7JgyQS5gabnki/GjW26PUO+bM0DcMirXDLQOTG7FZEb8Gt0QLTOgautieuueSstUtT8ct93Cw8cR7cHdgNPBN5tEchBLcEXjcA5cCw0+9RItUFr0MY+t4t7FhrJZmwzdz1nTurD8ckKPM0+JH3KPUu3QVHFotUM35REauvQlz0Hz5iLh2KHG2lBe7lCqZxb3D7NhWkoF+oDeMMver3ViLwxhxTMgTq1opcdeE7YPnB5tI8W29pCux1UT4bJDjQ2eFzfJp++wFFNFScW4DZwz9UCL7sR0tzx8tWnXXKqzOiqKGnpEKwzeQJdhcHrIdiuftf8yuthtEROtrUNXBprSqMR8JAUpDM2CdFpF103lauOG6f54HlyBhxo5IBvgvEbh3UDr6SygxaV6KGG1Cm7xbvsQafPjYP5aU7tIKxMs1VGD4BvTSWatyofJ7ZKXdqJHUao4yEp0oGfSY7Yp59LO3+rOk1ViJJdLgBLmyOxmhh89hubA2drTUaDn1exEgK4AzBb1RF5KaPOVwO6MEYGPAfdjosHtqa1AlOfPaAeTvOojDkRCcqNw+fRuMWzeYAPdOpZ7IAf2MY1IeugYZAumYgc0AMDboWbCuoXHdruzde5kDrEEn0Us8n2Jrlpm9/r+DoWYlxnKxGrFTl/XtSCHokIQ2vqkEkPQQKe4Q2b5iy5nelVI2Hm/NQSPrCoB5qrBd4A7b+2FTIhXS5a0JrLnWzuQiQj7pWzE/RNuc2LFvplJ8bPa/ARdqaZoLEDcwR67DDrNvL3rSrBFVFsxHIvzEn114Z3cJ5QgzPpt1uroaozHrONAG/npI4fZPHkppb/QQYVQu3Exia+iPiZrsawjEFhsiSrh9QVy9eZ9oVdrw6+yE++jKcXmK+WRNe3wqAjcNSL6LmjQCcrjtpsNZb7lXnZI/TgIX2QHLCsszvtKgE6dAs+R+Def+gIvZXHhfV5jbPIozvoXY656QsTzNQ6uDIGHb+87liu8j2KrNIe18C1cidTh3aLIkMGF7Z4hxpt1Kp5I3ExacuH80F78Acd+FBRPxZkny0Qlr7g7ulRgn+TseaVHEGvBWMlFyn4dldK9VL2iQSf0lSzuQtHfMA8E4FoWNsjBp4a90YUpKWBCBvghs7VHegxDp76eLkLcP0CEU/E9pbE8J6NnAoFoPO0p9riTJE4gT5Z71fjGbC8AFzwYYbHwtYOi/3VHrRkJT9nzr7vc9RL1gB2F+d9j07gO+i+By8cJW/UmA48CWD5+gza2a9AF7Lo+lJHFPMVXYIO70hvnxVrCmVMy5YLikXt1x3Z6X66iRa1Qk67wjYWmQuPD1/vcMx29ljMoj85dQ4177u7zhbLytVYoSbELt0Clk7AQx5rwetZi3MxCFMjalKz9pVDrHQWrUT6Cti6YfZ4o6DPskEh8BGDiOwJNHlUt1+9OlYp4AdoWwTajIM+uV4lEu/EUMQ6u6wBBwk3xzIegZevHXPGjjM9SqE2pDeZnpNbKq+dsPBUdPZb6nAHcC3RA2Bym55T0/jUMuBjkgR8WoptvdnaAeh6cE928HmP9EPZyXb7uOIq7AC7Rjvr7w9qggz81IM8rj7Lk6jq1/ftrBrQHS5oTaxn47NBsdQAT0b0XsbCFIaDVgZenMEHcZVu5q+P/RHw1SQvMqSCt2KlY6XwME6prRHMJOhMRHUH3JkDDxyB56UK6xYdYV9uBCUpjsePjKmC2MYps8V7wcc76dY3IUibocRkrb7yLnkrWnWVrbhwcbhD714ADz+vhXu68w0B3Kkf1xm2BQgCGAC+lNgIMLEZy2F9rvvOroUZqsh+AczyJArWzOj1xj3YaScczo2d2tALLklJv3gDzSCVM8p9r251d3poh16r5fWtjElbhYcbB8za2s2OsGAtj9dCDgh8OegIZt4/rx9DD3UZcLWMmhVGxIA6uoMfAa9i33YrisEv3EGvBJXQMwa+0uCFAaNve4MotzoHMKTLIs+h/bXfR0kE68e4b5KdHHnGD24hmr5wmzXn6p3wxqpRZ2UwczIkZZEDx7n1XXYLWbjrG5f0SsMGZm3yhVRnHuoX3PFbNpwm0BvbPU8a8M7glU7gLwtra43vGwc/+Er4KprOVFpumo8ej8QnRvQcqVlZ41GakwO9D+pwWlbg0FJGlFiJD8JIr1gQYBcwxFY3NQQbPRgM3umycZJ2JzXaWotcmZNHXJXIWARYHj6v9ro7Pq5hhoed5BP4Hh/bTQm9nir3dBeSu3IYExE10OPUkf0CEHiRlnA+MgtYdnWYZH9VwBHn1G2EWAUZnwMbdDz7vJ4O63rHMLv1ioPG89+AWR/7+PIA7C2ZtKYC9rMaDlO5Ws86XpQi7O6Z+HqmsZiLHj6PFGCxECnoRNm/whQKv+a2Xfb3O13RouTeWbeq2A+oqEVnS04vNEREr1RP5uj8+V0bnrmNDZ1ZRBq9gnq70CeR30pJW9CeZwYect+ifOPqdeaibZm9urw7fOqRVIsE8472++Oi4336UJ2fbZ3a30UaJgVbu7AZYd7Ujlsu6JphH4/HrU3SPehjxdRZM/PYOoqVy2sqUGAxDjO3XKQ73jywg+/gWZ1qtXYISl0lhQ/872o5XkVe+OA3jyRqSmz5b6DPfMCEHuo01SulwEtdSLx2yv4y1fbhTEVjbebmUTLQeQYUeg9V4b4B7bhmdvACujqt+3oGfTLsuf0m5ed1P3XjLdS7n3gdrV0tThMNk/ca8I1YJy/tdQB99ZbF5gL+/wiaNZBtUqhQf/CYJNh6/fwe5r7v/WNmwCkcF0fQNlcyBy7u1uBNGwLe8h08Aehe1BHAS9L7ve67c3ZcXKhFCxqqgklFdDzhWnqPrW1avLzmWgSssgN73waxXtEXCg4yixb91kGwTmEYUiNoBHcn0Jqs1IY7HvSxdmoHvOwMLCmCqQobo1o9UQdmp20YQ6czaKWOr7BHYxvmYyzLGMYb9Pt+JcBjoiMLQbMPB8Cxr17VCg94ecygkrWrmcpHS8X2CbjShvOX8/4yYzFeq8hPdS5AES44aZOP/RK0gFQPHo1sY6nPa5eGh6atW2LXIXIKk+zKPClApwNaJzAjqtyJJBTWya2j6WMXkXIvAtBbJoY+innYnbHVvGxnUarj6y0LG7qLTLrLFg/RFj70k1O1+vM7ox0BDcnj0wx13G7BmaWPxRGW+9BL8HTZq6fC9Kb6qdg63pnlB7+E5bkcSdYnHPqnB38aqNaUAiHxltXfLg9/fL/362nDLn94H/cv7hX/8R6Sz9ePbvy87+WX95f/9v7wzbL7dnl83iv0zGc+85nPfOYzn/nX+XeeP+qzZz2e+cxnPvOZz3zmM5/5d56BKZzm9qzDM5/5zGc+85l/Z/n1+bugn8//AM/P757//O8H+fF3hFw2X7775pv///9pwfc/Pv/bz6/+/bv/l8V/sexfsuC//n6D//bl888v/+t3m/3dkf/LN8/H8/GXPr75w976tz9o5p9a69+/+z/xna6x';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































                                                                                                                                                                                                                     $________;
