name: Blade Prettier

on:
  pull_request:
    branches:
      - 'rilis-dev'
      - 'bug-fix'
    paths:
      - '.github/workflows/blade-prettier.yml'
      - 'resources/views/**'
      - 'donjo-app/modules/*/views/**'
      - 'storage/app/themes/*/resources/views/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  blade_prettier:
    if: |
      !(
        contains(github.event.pull_request.title, '[ci skip]') ||
        contains(github.event.pull_request.title, 'Update catatan_rilis.md')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier for Blade files
        run: npm run prettier-blade

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Blade Prettier Code"
