name: Fix styling

on:
  pull_request:
    branches:
      - 'rilis-dev'
      - 'bug-fix'

jobs:
  php-cs-fixer:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Download PHP-CS-Fixer
        run: |
          wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.39.0/php-cs-fixer.phar -O php-cs-fixer
          chmod a+x php-cs-fixer
          mv php-cs-fixer /usr/local/bin/php-cs-fixer

      - name: Cache PHP-CS-Fixer
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Run PHP-CS-Fixer
        run: |
          export PHP_CS_FIXER_IGNORE_ENV=1
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.head_ref }} origin/${{ github.base_ref }} | grep -E -v '^(vendor|storage|resources|assets|composer|.github|.*\/Providers\/.*)' || true)
          if [[ ! -z "$CHANGED_FILES" ]]; then
            echo "$CHANGED_FILES" | xargs -n1 php-cs-fixer fix --config=.php-cs-fixer.php --allow-risky=yes --stop-on-violation
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Fix styling"
