name: Refactor Rector

on:
  pull_request:
    branches:
      - 'rilis-dev'
      - 'bug-fix'
    paths:
      - '.github/workflows/refactor-rector.yml'
      - 'donjo-app/**'
      - 'app/**'

jobs:
  rector:
    if: |
      !(
        contains(github.event.pull_request.title, '[ci skip]') ||
        contains(github.event.pull_request.title, 'Update catatan_rilis.md')
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Remove existing dependencies and lock file
        run: rm -rf vendor composer.lock

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Install Rector
        run: composer require --dev rector/rector:1.0.3

      - name: Cache Rector Files
        uses: actions/cache@v3
        with:
          path: .rector-cache
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-rector-

      - name: Generate Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.head_ref }} origin/${{ github.base_ref }} \
          | grep -E -v '^(vendor|composer.json|composer.lock|resources|assets)' \
          | grep -Ev 'ConsoleServiceProvider.php' || true)
          echo "::set-output name=files::${CHANGED_FILES}"

      - name: Run Rector on Changed Files
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | xargs -r rector process --ansi --debug || echo "Rector completed with warnings/errors."

      - name: Auto Commit Refactored Code
        if: steps.changed-files.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[code-refactor] Rector Refactor Code'
          file_pattern: ':!assets/ :!vendor/ :!composer.json :!composer.lock'
