name: Refactor Rector

on:
  pull_request:
    branches:
      - 'rilis-dev'
      - 'bug-fix'
    paths:
      - '.github/workflows/refactor-rector.yml'
      - 'donjo-app/**'
      - 'app/**'

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Rector
        run: composer global require rector/rector:1.0.3

      - name: Cache Rector Files
        uses: actions/cache@v3
        with:
          path: .cache-rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-rector-

      - name: Generate Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff --name-only --diff-filter=d origin/${{ github.head_ref }} origin/${{ github.base_ref }} \
          | grep -E -v '^(vendor|resources|assets|composer)' \
          | grep -Ev 'ConsoleServiceProvider.php' \
          || echo ""

      - name: Run Rector on Changed Files
        if: steps.changed-files.outputs.files
        run: |
          xargs -a <(echo "${{ steps.changed-files.outputs.files }}") \
          rector process --ansi --debug || echo "Rector completed with warnings/errors."

      - name: Auto Commit Refactored Code
        if: steps.changed-files.outputs.files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[code-refactor] Rector Refactor Code'
