name: Unit Test

on:
  pull_request:
    branches:
      - 'rilis-dev'
      - 'bug-fix'

jobs:
  test:
    if: |
      !(
        contains(github.event.pull_request.title, '[ci skip]') ||
        contains(github.event.pull_request.title, 'Update catatan_rilis.md')
      )
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, mysqli, pdo, pdo_mysql, fileinfo, intl, bcmath, tokenizer, ctype, json, openssl, gd, tidy, zip, dom, curl, libxml, pcntl, sqlite, pdo_sqlite, soap, exif, iconv
          coverage: none

      - name: Remove existing dependencies and lock file
        run: rm -rf vendor composer.lock

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Ensure phpunit is executable
        run: chmod +x vendor/bin/phpunit

      - name: Run tests
        run: vendor/bin/phpunit
